Bomberman: Menu.PlayerInGameMenuHandler Class Reference
Menu.PlayerInGameMenuHandler Class Reference
Handles the player ingame menus
Public Member Functions
void SetUpPanel (Player player)
Displays the player with it's current health Should be used for reseting only!
void RemoveHealth ()
Remove a health from the display
void AddBonus (BonusType type, Sprite bonusImage)
Adds a new bonus to the display
void RemoveBonus (BonusType type)
Removes a bonus from the display
Private Member Functions
void AddHealth ()
Add a new health icon to the display
void ReorganizeBonuses ()
Reorganizes the bonuses positions
void RemoveBonusWithoutReorganize (BonusType type)
Removes a bonus without reorganizing the displays
Private Attributes
Sprite healthSprite
The sprite of the health icons
GameObject healthBarContainer
Where to put the health icons
GameObject bonusesContainer
Where to put the bonus icons
UnityEngine.UI.Image playerIconImage
Player skin display
TMP_Text playerName
Player name display
TMP_Text ScoreText
Player score display
int currentHealth = 0
The current health which are displayed
Dictionary< BonusType, RectTransform > bonuses = new Dictionary<BonusType, RectTransform>()
The bonuses which are displayed
List< GameObject > healthIcons = new List<GameObject>()
The health icons which are displayed right now
Detailed Description
Handles the player ingame menus
Definition at line 15 of file PlayerInGameMenuHandler.cs.
Member Function Documentation
SetUpPanel()
void Menu.PlayerInGameMenuHandler.SetUpPanel (Player player) inline
Displays the player with it's current health Should be used for reseting only!
Parameters
player The player to display
Definition at line 73 of file PlayerInGameMenuHandler.cs.
         {
             playerName.text = player.PlayerName;
             playerIconImage.sprite = player.gameObject.GetComponent<SpriteRenderer>().sprite;
             while (bonuses.Count > 0)
             {
                 RemoveBonusWithoutReorganize(bonuses.ElementAt(0).Key);
             }
             while (currentHealth > player.Hp)
             {
                 RemoveHealth();
             }
             for (int i = currentHealth; i < player.Hp; i++)
             {
                 AddHealth();
             }
             ScoreText.text = player.Score.ToString();
         }
References Menu.PlayerInGameMenuHandler.AddHealth(), Menu.PlayerInGameMenuHandler.bonuses, Menu.PlayerInGameMenuHandler.currentHealth, Bomberman.MovingEntity.Hp, Menu.PlayerInGameMenuHandler.playerIconImage, Bomberman.Player.PlayerName, Menu.PlayerInGameMenuHandler.playerName, Menu.PlayerInGameMenuHandler.RemoveBonusWithoutReorganize(), Menu.PlayerInGameMenuHandler.RemoveHealth(), Bomberman.Player.Score, and Menu.PlayerInGameMenuHandler.ScoreText.
Referenced by Menu.MenuController.NewGame().
AddHealth()
void Menu.PlayerInGameMenuHandler.AddHealth () inline private
Add a new health icon to the display
Definition at line 98 of file PlayerInGameMenuHandler.cs.
         {
             currentHealth++;
             GameObject healthGameObject = new GameObject("health" + currentHealth, typeof(UnityEngine.UI.Image));
             healthGameObject.transform.SetParent(healthBarContainer.transform);
             Image healthImage = healthGameObject.GetComponent<Image>();
             RectTransform rectTransform = healthImage.GetComponent<RectTransform>();
             healthImage.sprite = healthSprite;
             rectTransform.anchorMin = new Vector2(0, 0.5f);
             rectTransform.anchorMax = new Vector2(0, 0.5f);
             rectTransform.localScale = Vector3.one;
             rectTransform.localPosition = new Vector2(-30 + (currentHealth - 1) * 30, 0);
             rectTransform.sizeDelta = new Vector2(30, 30);
             healthIcons.Add(healthGameObject);
         }
References Menu.PlayerInGameMenuHandler.currentHealth, Menu.PlayerInGameMenuHandler.healthBarContainer, Menu.PlayerInGameMenuHandler.healthIcons, and Menu.PlayerInGameMenuHandler.healthSprite.
Referenced by Menu.PlayerInGameMenuHandler.SetUpPanel().
RemoveHealth()
void Menu.PlayerInGameMenuHandler.RemoveHealth () inline
Remove a health from the display
Exceptions
NullReferenceException
Definition at line 118 of file PlayerInGameMenuHandler.cs.
         {
             if (currentHealth <= 0)
             {
                 throw new NullReferenceException("No health to remove");
             }
             currentHealth--;
             Destroy(healthIcons[currentHealth]);
             healthIcons.RemoveAt(currentHealth);
         }
References Menu.PlayerInGameMenuHandler.currentHealth, and Menu.PlayerInGameMenuHandler.healthIcons.
Referenced by Menu.MenuController.RemoveHealth(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
AddBonus()
void Menu.PlayerInGameMenuHandler.AddBonus (BonusType type, Sprite bonusImage) inline
Adds a new bonus to the display
Parameters
type The type of the bonus to display
bonusImage The bonus's image to display
Definition at line 136 of file PlayerInGameMenuHandler.cs.
         {
             GameObject bonusGameObject = new GameObject("bonusIcon" + type.ToString(), typeof(UnityEngine.UI.Image));
             bonusGameObject.transform.SetParent(bonusesContainer.transform);
             Image bonusImageComp = bonusGameObject.GetComponent<Image>();
             RectTransform rectTransform = bonusImageComp.GetComponent<RectTransform>();
             bonusImageComp.sprite = bonusImage;
             rectTransform.anchorMin = new Vector2(0, 1f);
             rectTransform.anchorMax = new Vector2(0, 1f);
             rectTransform.localScale = Vector3.one;
             rectTransform.localPosition = new Vector2(-40 + (bonuses.Count % 4) * 30, 20 - (bonuses.Count / 4) * 30);
             rectTransform.sizeDelta = new Vector2(30, 30);
             bonuses.Add(type, rectTransform);
             if (bonuses.Count > 8)
             {
                 bonusGameObject.SetActive(false);
             }
             //bonuses.Add(type);
         }
References Menu.PlayerInGameMenuHandler.bonuses, and Menu.PlayerInGameMenuHandler.bonusesContainer.
Referenced by Menu.MenuController.AddBonus().
RemoveBonus()
void Menu.PlayerInGameMenuHandler.RemoveBonus (BonusType type) inline
Removes a bonus from the display
Parameters
type The bonus type to remove
Definition at line 161 of file PlayerInGameMenuHandler.cs.
         {
             RemoveBonusWithoutReorganize(type);
             ReorganizeBonuses();
         }
References Menu.PlayerInGameMenuHandler.RemoveBonusWithoutReorganize(), and Menu.PlayerInGameMenuHandler.ReorganizeBonuses().
Referenced by Menu.MenuController.RemoveBonus().
ReorganizeBonuses()
void Menu.PlayerInGameMenuHandler.ReorganizeBonuses () inline private
Reorganizes the bonuses positions
Definition at line 171 of file PlayerInGameMenuHandler.cs.
         {
             int counter = 0;
             foreach (var bonus in bonuses)
             {
                 if (counter >= 8)
                 {
                     bonus.Value.gameObject.SetActive(false);
                 }
                 else
                 {
                     bonus.Value.gameObject.SetActive(true);
                 }
                 bonus.Value.transform.localPosition = new Vector2(-40 + (counter % 4) * 30, 20 - (counter / 4) * 30);
                 counter++;
             }
         }
References Menu.PlayerInGameMenuHandler.bonuses.
Referenced by Menu.PlayerInGameMenuHandler.RemoveBonus().
RemoveBonusWithoutReorganize()
void Menu.PlayerInGameMenuHandler.RemoveBonusWithoutReorganize (BonusType type) inline private
Removes a bonus without reorganizing the displays
Parameters
type The bonus to remove
Definition at line 195 of file PlayerInGameMenuHandler.cs.
         {
             Destroy(bonuses[type].gameObject);
             bonuses.Remove(type);
         }
References Menu.PlayerInGameMenuHandler.bonuses.
Referenced by Menu.PlayerInGameMenuHandler.RemoveBonus(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
Member Data Documentation
healthSprite
Sprite Menu.PlayerInGameMenuHandler.healthSprite private
The sprite of the health icons
Definition at line 21 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddHealth().
healthBarContainer
GameObject Menu.PlayerInGameMenuHandler.healthBarContainer private
Where to put the health icons
Definition at line 27 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddHealth().
bonusesContainer
GameObject Menu.PlayerInGameMenuHandler.bonusesContainer private
Where to put the bonus icons
Definition at line 33 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddBonus().
playerIconImage
UnityEngine.UI.Image Menu.PlayerInGameMenuHandler.playerIconImage private
Player skin display
Definition at line 39 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.SetUpPanel().
playerName
TMP_Text Menu.PlayerInGameMenuHandler.playerName private
Player name display
Definition at line 45 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.SetUpPanel().
ScoreText
TMP_Text Menu.PlayerInGameMenuHandler.ScoreText private
Player score display
Definition at line 51 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.SetUpPanel().
currentHealth
int Menu.PlayerInGameMenuHandler.currentHealth = 0 private
The current health which are displayed
Definition at line 56 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddHealth(), Menu.PlayerInGameMenuHandler.RemoveHealth(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
bonuses
Dictionary<BonusType, RectTransform> Menu.PlayerInGameMenuHandler.bonuses = new Dictionary<BonusType, RectTransform>() private
The bonuses which are displayed
Definition at line 61 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddBonus(), Menu.PlayerInGameMenuHandler.RemoveBonusWithoutReorganize(), Menu.PlayerInGameMenuHandler.ReorganizeBonuses(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
healthIcons
List<GameObject> Menu.PlayerInGameMenuHandler.healthIcons = new List<GameObject>() private
The health icons which are displayed right now
Definition at line 66 of file PlayerInGameMenuHandler.cs.
Referenced by Menu.PlayerInGameMenuHandler.AddHealth(), and Menu.PlayerInGameMenuHandler.RemoveHealth().
The documentation for this class was generated from the following file:
Assets/Scripts/Menu/PlayerInGameMenuHandler.cs