Bomberman: Bomberman.Player Class Reference
Bomberman.Player Class Reference
Every player will be derived from this class
Public Member Functions
void OnCollisionEnter2D (Collision2D collision)
Check for collision with the elements
void OnCollisionExit2D (Collision2D collision)
Check for collision with the battle royale circle, if collided it kills the player instant
override void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Initialize the player object with base values
void LoadPlayer (PlayerSave playerSave, GameBoard gameBoard, List< Obstacle > playerObstacles)
Loads in the player
override bool Kill ()
Override the kill event so we can check for game over
void ChangeName (string newName)
Changes the player's name
void AddScore ()
Increase the score of the player
Public Member Functions inherited from Bomberman.MovingEntity
void InstantKill ()
Instantly kill the entity it's health and immuneTime doesn't matter
bool DirectionPassable (Direction dir)
Checks if the given direction is passable for the entity
virtual void ChangedCell (int boardRow, int boardCol)
Called when an entity changed it's cell on the board
void SetGhost (bool newValue)
Called when we want to set this moving entity type to ghost or not ghost
Public Attributes
EventHandler PlayerDiedEventHandler
Event to call when the player died
Public Attributes inherited from Bomberman.MovingEntity
EventHandler ReachedTargetEvent
Event which is called when it changed tiles completely
Properties
string PlayerName [get, private set]
The player's name
Dictionary< BonusType, Bonus > Bonuses = new Dictionary<BonusType, Bonus>() [get, private set]
The bonuses active for the player
Dictionary< KeyCode, Action > Controls = new Dictionary<KeyCode, Action>() [get, private set]
The control's for the player
List< Bomb > Bombs = new List<Bomb>() [get, private set]
The bomb's of the player
int Score = 0 [get, private set]
The current score of the player
int PlayerId [get]
The id of the player
int AvailableObstacle = 0 [get, private set]
How much placeable obstacle does the player has
float ImmunityMaxDuration [get, private set]
The max duration of the players immunity
float GhostMaxDuration [get, private set]
The max duration of how much time the player can be a ghost
Properties inherited from Bomberman.MovingEntity
float ImmuneTime = 0f [get, protected set]
float Speed [get, protected set]
Speed of the entity (how fast it will move on the board)
int Hp [get, protected set]
How many times can the entity be "killed"
bool Alive = true [get, protected set]
Is the entity alive
Direction CurrentDirection = Direction.Left [get, protected set]
The current moving direction of the entity
float moveProgress [get, private set]
How is the move progressing (0.0-1.0)
float timeToMove = 1f [get, protected set]
How long does the movement take
Properties inherited from Bomberman.MapEntity
Position CurrentBoardPos [get, protected set]
The entity's current position on the Board's grid
MapEntityType EntityType [get, protected set]
The type of the entity
GameBoard GameBoard [get, protected set]
Reference to the parent board
Private Member Functions
void Awake ()
When the script is loaded this method is called
void Start ()
Start is called before the first frame update
new void Update ()
Update is called once per frame
void MoveLeft ()
Changes the player's direction to left
void MoveUp ()
Changes the player's direction to up
void MoveRight ()
Changes the player's direction to right
void MoveDown ()
Changes the player's direction to down
void PlaceBomb ()
The player places a bomb on the board if it has a bomb available
void PlaceObstacle ()
The player places a bomb on the board if it has a wall available
void PlacedObstacleBlownUp (object obj, EventArgs args)
This methid is called when someone blows up one of the players obstacles
void HandleKeys ()
Handles the keypresses
bool AllTheBombsPlaced ()
Check if all the bombs placed
Private Attributes
float actionCooldown = 0f
int playerId
string playerName = "player"
GameObject bombPrefab
SpriteRenderer spriteRenderer
The player's display
Additional Inherited Members
Protected Member Functions inherited from Bomberman.MovingEntity
void Update ()
Called every frame update
virtual bool Move (Direction dir)
What Moves the entity at the direction
void ChangeDir (Direction dir)
Changes the direction of the entity
Protected Attributes inherited from Bomberman.MovingEntity
Direction NewDirection = Direction.None
Detailed Description
Every player will be derived from this class
Definition at line 16 of file Player.cs.
Member Function Documentation
Awake()
void Bomberman.Player.Awake () inline private
When the script is loaded this method is called
Definition at line 89 of file Player.cs.
         {
             if (playerId > 2)
             {
                 Debug.LogError("PlayerId can't be higher than 2");
             }
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("UpButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 0].ToString())), MoveUp);
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("DownButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 1].ToString())), MoveDown);
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("RightButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 2].ToString())), MoveRight);
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("LeftButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 3].ToString())), MoveLeft);
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("PlacingBombButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 4].ToString())), PlaceBomb);
             Controls.Add((KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("PlacingObstacleButton" + playerId, Config.PLAYERDEFAULTKEYS[playerId, 5].ToString())), PlaceObstacle);
             spriteRenderer = this.gameObject.GetComponent<SpriteRenderer>();
             if (spriteRenderer != null)
             {
                 spriteRenderer.sprite = Resources.Load<Sprite>("PlayerSkins/" + MainMenuConfig.PlayerSkins[playerId]);
             }
             else
             {
                 Debug.LogError("No sprite renderer connected to the player script's gameobject");
             }
         }
References Bomberman.Player.Controls, Bomberman.Player.MoveDown(), Bomberman.Player.MoveLeft(), Bomberman.Player.MoveRight(), Bomberman.Player.MoveUp(), Bomberman.Player.PlaceBomb(), Bomberman.Player.PlaceObstacle(), Bomberman.Config.PLAYERDEFAULTKEYS, Bomberman.Player.playerId, Menu.MainMenuConfig.PlayerSkins, and Bomberman.Player.spriteRenderer.
Start()
void Bomberman.Player.Start () inline private
Start is called before the first frame update
Definition at line 117 of file Player.cs.
         {
         }
Update()
new void Bomberman.Player.Update () inline private
Update is called once per frame
Definition at line 124 of file Player.cs.
         {
             if (GameBoard.Paused)
             {
                 return;
             }
             if (actionCooldown > 0f)
             {
                 actionCooldown -= Time.deltaTime;
             }
             for (int i = 0; i < Bonuses.Keys.Count; i++)
             {
                 Bonus bonus = Bonuses.ElementAt(i).Value;
                 if (bonus.Decaying)
                 {
                     if (bonus.DecreaseDuration(Time.deltaTime))
                     {
                         switch (bonus.Type)
{
                             case BonusType.Slowness:
                                 if (Bonuses.ContainsKey(BonusType.Skate))
{
                                     this.timeToMove = 1 / (float)(this.Speed * 1.3f);
                                 }
                                 else
{
                                     this.timeToMove = 1f / this.Speed;
                                 }
                                 break;
                             case BonusType.Ghost:
                                 if (GameBoard.Cells[CurrentBoardPos.Row, CurrentBoardPos.Col].Placed && !GameBoard.Cells[CurrentBoardPos.Row, CurrentBoardPos.Col].HasBomb)
{
                                     InstantKill();
                                 }
                                 spriteRenderer.color = new Color(spriteRenderer.color.r, spriteRenderer.color.g, spriteRenderer.color.b, 1);
                                 this.SetGhost(false);
                                 break;
                             case BonusType.Immunity:
                                 spriteRenderer.color = new Color(1, 1, 1, spriteRenderer.color.a);
                                 break;
                             default:
                                 break;
                         }
                         this.GameBoard.MenuController.RemoveBonus(bonus.Type, this);
                         Destroy(bonus.gameObject);
                         Bonuses.Remove(bonus.Type);
                     }
                 }
             }
             if (Bonuses.ContainsKey(BonusType.InstantBomb))
             {
                 PlaceBomb();
             }
             if (Bonuses.ContainsKey(BonusType.Immunity))
             {
                 spriteRenderer.color = new Color(1, 1 - Bonuses[BonusType.Immunity].Duration / ImmunityMaxDuration, 1 - Bonuses[BonusType.Immunity].Duration / ImmunityMaxDuration, spriteRenderer.color.a);
             }
             if (Bonuses.ContainsKey(BonusType.Ghost))
             {
                 spriteRenderer.color = new Color(spriteRenderer.color.r, spriteRenderer.color.g, spriteRenderer.color.b, 1 - Bonuses[BonusType.Ghost].Duration / (GhostMaxDuration * 2));
             }
             HandleKeys();
             base.Update();
         }
References Bomberman.Player.actionCooldown, Bomberman.Player.Bonuses, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bonus.Decaying, Bomberman.Bonus.DecreaseDuration(), Bomberman.Player.GhostMaxDuration, Bomberman.Player.HandleKeys(), Bomberman.Obstacle.HasBomb, Bomberman.Player.ImmunityMaxDuration, Bomberman.MovingEntity.InstantKill(), Bomberman.GameBoard.MenuController, Bomberman.GameBoard.Paused, Bomberman.Player.PlaceBomb(), Bomberman.Obstacle.Placed, Menu.MenuController.RemoveBonus(), DataTypes.Position.Row, Bomberman.MovingEntity.SetGhost(), Bomberman.MovingEntity.Speed, Bomberman.Player.spriteRenderer, Bomberman.MovingEntity.timeToMove, and Bomberman.Bonus.Type.
OnCollisionEnter2D()
void Bomberman.Player.OnCollisionEnter2D (Collision2D collision) inline
Check for collision with the elements
Parameters
collision What it collided with
Definition at line 199 of file Player.cs.
         {
             switch (collision.gameObject.tag)
             {
                 case "Monster":
                     this.Kill();
                     break;
                 case "Bonus":
                     Bonus bonus = collision.gameObject.GetComponent<Bonus>();
                     Debug.Log("Picked up " + bonus.name);
                     if (!Bonuses.ContainsKey(bonus.Type))
                     {
                         Bonuses.Add(bonus.Type, bonus);
                         GameBoard.MenuController.AddBonus(bonus.Type, this);
                     }
                     switch (bonus.Type)
                     {
                         //If this bonus is picked up it increases the player bomb count by one
                         case BonusType.BonusBomb:
                             if (Bonuses[bonus.Type].IncreaseTier())
{
                                 Bomb bomb1 = Instantiate(bombPrefab, this.GameBoard.gameObject.transform).GetComponent<Bomb>();
                                 bomb1.Init(MapEntityType.Bomb, this.GameBoard, this.CurrentBoardPos);
                                 this.Bombs.Add(bomb1);
                             }
                             break;
                         //If this bonus is picked up it increases the player bombs range by one
                         case BonusType.BombRange:
                             Bonuses[bonus.Type].IncreaseTier();
                             break;
                         //If this bonus is picked up the player slowes down
                         case BonusType.Slowness:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("Slowness effect started");
                             this.timeToMove = 1 / (float)(this.Speed * 0.6f);
                             //Missing: This effect lasts for a period of time
                             break;
                         //If this bonus is picked up it decreases the player bombs range
                         case BonusType.SmallExplosion:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("SmallExplosion effect started");
                             //Missing: This effect lasts for a period of time
                             break;
                         //If this bonus is picked up it is temporarily disables the bomb placement for the player
                         case BonusType.NoBomb:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("No bomb activated");
                             break;
                         //If this bonus is picked up the player will place down all its bombs
                         case BonusType.InstantBomb:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("InstantBomb effect started");
                             break;
                         //If this bonus is picked up the player will be able to detonate its bombs, however only after placing all of them and they dont
                         //blow up with time
                         case BonusType.Detonator:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("Detonator bonus picked up");
                             foreach (Bomb bomb in Bombs)
{
                                 bomb.Detonable = true;
                             }
                             break;
                         //If this bonus is picked up the player speed will be increased
                         case BonusType.Skate:
                             Bonuses[bonus.Type].IncreaseTier();
                             Debug.Log("Skate bonus picked up");
                             if (!Bonuses.ContainsKey(BonusType.Slowness))
                                 this.timeToMove = 1 / (float)(this.Speed * 1.3f);
                             break;
                         //If this bonus is picked up the player will be immune for damage for a short peroid of time
                         case BonusType.Immunity:
                             Bonuses[bonus.Type].IncreaseTier();
                             ImmunityMaxDuration = bonus.Duration;
                             spriteRenderer.color = new Color(1, 0, 0, spriteRenderer.color.a);
                             break;
                         case BonusType.Ghost:
                             Bonuses[bonus.Type].IncreaseTier();
                             spriteRenderer.color = new Color(spriteRenderer.color.r, spriteRenderer.color.g, spriteRenderer.color.b, 0.5f);
                             GhostMaxDuration = bonus.Duration;
                             this.SetGhost(true);
                             break;
                         case BonusType.Obstacle:
                             if (Bonuses[bonus.Type].IncreaseTier())
{
                                 AvailableObstacle += 3;
                             }
                             break;
                         default:
                             break;
                     }
                     if (bonus.Decaying)
                     {
                         this.GameBoard.Entites.Remove(bonus);
                         if (bonus != Bonuses[bonus.Type])
{
                             this.GameBoard.Entites.Remove(bonus);
                             Destroy(bonus.gameObject);
                         }
                         else
{
                             bonus.Hide();
                         }
                         Bonuses[bonus.Type].ResetDecayingBonus(bonus.Duration);
                     }
                     else if (Bonuses[bonus.Type].Tier == 1)
                     {
                         bonus.Hide();
                     }
                     else
                     {
                         bonus.Hide();
                         this.GameBoard.Entites.Remove(bonus);
                         Destroy(bonus.gameObject);
                     }
                     break;
                 default:
                     break;
             }
         }
References Menu.MenuController.AddBonus(), Bomberman.Player.AvailableObstacle, Bomberman.Player.bombPrefab, Bomberman.Player.Bombs, Bomberman.Player.Bonuses, Bomberman.Bonus.Decaying, Bomberman.Bomb.Detonable, Bomberman.Bonus.Duration, Bomberman.GameBoard.Entites, Bomberman.Player.GhostMaxDuration, Bomberman.Bonus.Hide(), Bomberman.Player.ImmunityMaxDuration, Bomberman.MapEntity.Init(), Bomberman.Player.Kill(), Bomberman.GameBoard.MenuController, Bomberman.MovingEntity.SetGhost(), Bomberman.MovingEntity.Speed, Bomberman.Player.spriteRenderer, Bomberman.MovingEntity.timeToMove, and Bomberman.Bonus.Type.
OnCollisionExit2D()
void Bomberman.Player.OnCollisionExit2D (Collision2D collision) inline
Check for collision with the battle royale circle, if collided it kills the player instant
Definition at line 335 of file Player.cs.
         {
             Debug.Log(collision.gameObject.tag);
             if (collision.gameObject.tag == "Circle")
             {
                 InstantKill();
             }
         }
References Bomberman.MovingEntity.InstantKill().
MoveLeft()
void Bomberman.Player.MoveLeft () private
Changes the player's direction to left
Referenced by Bomberman.Player.Awake().
MoveUp()
void Bomberman.Player.MoveUp () private
Changes the player's direction to up
Referenced by Bomberman.Player.Awake().
MoveRight()
void Bomberman.Player.MoveRight () private
Changes the player's direction to right
Referenced by Bomberman.Player.Awake().
MoveDown()
void Bomberman.Player.MoveDown () private
Changes the player's direction to down
Referenced by Bomberman.Player.Awake().
PlaceBomb()
void Bomberman.Player.PlaceBomb () inline private
The player places a bomb on the board if it has a bomb available
Definition at line 367 of file Player.cs.
         {
             if (actionCooldown > 0)
             {
                 return;
             }
             if (Bonuses.ContainsKey(BonusType.Detonator))
             {
                 if (AllTheBombsPlaced())
                 {
                     foreach (Bomb bomb in Bombs)
                     {
                         bomb.BlowUp();
                     }
                 }
             }
             if (Bonuses.ContainsKey(BonusType.NoBomb) || GameBoard.Cells[this.CurrentBoardPos.Row, this.CurrentBoardPos.Col].Placed)
             {
                 return;
             }
             actionCooldown = Config.PLAYERACTIONCOOLDOWN;
             foreach (Bomb bomb in Bombs)
             {
                 if (!bomb.Placed)
                 {
                     int bombRange = Config.BOMBDEFAULTEXPLOSIONRANGE;
                     if (Bonuses.ContainsKey(BonusType.BombRange))
                     {
                         bombRange += Bonuses[BonusType.BombRange].Tier;
                     }
                     if (Bonuses.ContainsKey(BonusType.SmallExplosion))
                     {
                         bombRange = 1;
                     }
                     bomb.Place(new Position(this.CurrentBoardPos.Row, this.CurrentBoardPos.Col), bombRange);
                     GameBoard.Cells[this.CurrentBoardPos.Row, this.CurrentBoardPos.Col].PlaceBomb(bomb);
                     return;
                 }
             }
             //throw new System.NotImplementedException();
         }
References Bomberman.Player.actionCooldown, Bomberman.Player.AllTheBombsPlaced(), Bomberman.Bomb.BlowUp(), Bomberman.Config.BOMBDEFAULTEXPLOSIONRANGE, Bomberman.Player.Bombs, Bomberman.Player.Bonuses, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bomb.Place(), Bomberman.Obstacle.PlaceBomb(), Bomberman.Bomb.Placed, Bomberman.Obstacle.Placed, Bomberman.Config.PLAYERACTIONCOOLDOWN, and DataTypes.Position.Row.
Referenced by Bomberman.Player.Awake(), and Bomberman.Player.Update().
PlaceObstacle()
void Bomberman.Player.PlaceObstacle () inline private
The player places a bomb on the board if it has a wall available
Definition at line 417 of file Player.cs.
         {
             if (actionCooldown > 0 || !Bonuses.ContainsKey(BonusType.Obstacle) || AvailableObstacle <= 0)
             {
                 return;
             }
             actionCooldown = Config.PLAYERACTIONCOOLDOWN;
             Obstacle obstacle = GameBoard.Cells[CurrentBoardPos.Row, CurrentBoardPos.Col];
             if (!obstacle.Placed)
             {
                 AvailableObstacle--;
                 obstacle.Place(false, playerId);
                 obstacle.BlownUp = PlacedObstacleBlownUp;
             }
         }
References Bomberman.Player.actionCooldown, Bomberman.Player.AvailableObstacle, Bomberman.Obstacle.BlownUp, Bomberman.Player.Bonuses, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Obstacle.Place(), Bomberman.Obstacle.Placed, Bomberman.Player.PlacedObstacleBlownUp(), Bomberman.Config.PLAYERACTIONCOOLDOWN, Bomberman.Player.playerId, and DataTypes.Position.Row.
Referenced by Bomberman.Player.Awake().
PlacedObstacleBlownUp()
void Bomberman.Player.PlacedObstacleBlownUp (object obj, EventArgs args) inline private
This methid is called when someone blows up one of the players obstacles
Definition at line 437 of file Player.cs.
         {
             ++AvailableObstacle;
         }
References Bomberman.Player.AvailableObstacle.
Referenced by Bomberman.Player.LoadPlayer(), and Bomberman.Player.PlaceObstacle().
Init()
override void Bomberman.Player.Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos) inline virtual
Initialize the player object with base values
Reimplemented from Bomberman.MovingEntity.
Definition at line 445 of file Player.cs.
         {
             base.Init(entityType, gameBoard, CurrentPos);
             this.SetGhost(false);
             //Reset the player's components
             while (Bombs.Count != 0)
             {
                 Destroy(Bombs[0].gameObject);
                 Bombs.RemoveAt(0);
             }
             foreach (BonusType bonus in Enum.GetValues(typeof(BonusType)))
             {
                 if (Bonuses.ContainsKey(bonus))
                 {
                     Bonuses.Remove(bonus);
                 }
             }
             Bomb bomb1 = Instantiate(bombPrefab, this.GameBoard.gameObject.transform).GetComponent<Bomb>();
             bomb1.Init(MapEntityType.Bomb, this.GameBoard, this.CurrentBoardPos);
             Bombs.Add(bomb1);
         }
References Bomberman.Player.bombPrefab, Bomberman.Player.Bombs, Bomberman.Player.Bonuses, Bomberman.MapEntity.Init(), and Bomberman.MovingEntity.SetGhost().
LoadPlayer()
void Bomberman.Player.LoadPlayer (PlayerSave playerSave, GameBoard gameBoard, List< Obstacle > playerObstacles) inline
Loads in the player
Parameters
playerSave The player's save to load
gameBoard The parent gameBoard of the player
playerObstacles The obstacles which was placed by this player
Definition at line 476 of file Player.cs.
         {
             //Reset the player's components
             while (Bombs.Count != 0)
             {
                 Destroy(Bombs[0].gameObject);
                 Bombs.RemoveAt(0);
             }
             //Clear the player's bonuses if it has any
             foreach (BonusType bonus in Enum.GetValues(typeof(BonusType)))
             {
                 if (Bonuses.ContainsKey(bonus))
                 {
                     Bonuses.Remove(bonus);
                 }
             }
             //Change every field to match the save's fields
             base.Init(MapEntityType.Player, gameBoard, playerSave.CurrentBoardPos);
             this.SetGhost(false);
             this.Score = playerSave.Score;
             this.Alive = playerSave.Alive;
             this.Hp = playerSave.Hp;
             this.ImmuneTime = playerSave.ImmuneTime;
             this.CurrentDirection = playerSave.CurrentDirection;
             this.playerName = playerSave.PlayerName;
             //Load the bonuses
             foreach (var item in playerSave.Bonuses)
             {
                 switch (item.Type)
                 {
                     case BonusType.Immunity:
                         break;
                     case BonusType.Ghost:
                         this.SetGhost(true);
                         break;
                     case BonusType.Skate:
                         if (!Bonuses.ContainsKey(BonusType.Slowness))
{
                             this.timeToMove = 1 / (float)(this.Speed * 1.3f);
                         }
                         break;
                     case BonusType.Slowness:
                         this.timeToMove = 1 / (float)(this.Speed * 0.6f);
                         break;
                     default:
                         break;
                 }
                 Bonus bonus = Instantiate(gameBoard.BonusPrefabs[item.Type], this.GameBoard.gameObject.transform).GetComponent<Bonus>();
                 bonus.gameObject.transform.transform.localPosition = new Vector3(CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - CurrentBoardPos.Row * Config.CELLSIZE, 1);
                 bonus.Init(MapEntityType.Bonus, this.GameBoard, new Position(this.CurrentBoardPos.Row, this.CurrentBoardPos.Col));
                 bonus.LoadBonus(item);
                 Bonuses.Add(item.Type, bonus);
             }
             //Load the bombs
             foreach (var item in playerSave.Bombs)
             {
                 Bomb bomb1 = Instantiate(bombPrefab, this.GameBoard.gameObject.transform).GetComponent<Bomb>();
                 bomb1.Init(MapEntityType.Bomb, this.GameBoard, item.CurrentBoardPos);
                 bomb1.LoadBomb(item);
                 Bombs.Add(bomb1);
             }
             this.AvailableObstacle = playerSave.AvailableObstacle;
             //Set the display timers
             this.GhostMaxDuration = playerSave.GhostMaxDuration;
             this.ImmunityMaxDuration = playerSave.ImmunityMaxDuration;
             //Add the events to the player's owned obstacles
             foreach (var item in playerObstacles)
             {
                 item.BlownUp = this.PlacedObstacleBlownUp;
             }
         }
References Bomberman.MovingEntity.Alive, Bomberman.Player.AvailableObstacle, Bomberman.Player.bombPrefab, Bomberman.Player.Bombs, Bomberman.Player.Bonuses, Bomberman.Config.CELLSIZE, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.MovingEntity.CurrentDirection, Bomberman.Player.GhostMaxDuration, Bomberman.MovingEntity.Hp, Bomberman.MovingEntity.ImmuneTime, Bomberman.Player.ImmunityMaxDuration, Bomberman.Bonus.Init(), Bomberman.MapEntity.Init(), Bomberman.Bomb.LoadBomb(), Bomberman.Bonus.LoadBonus(), Bomberman.Player.PlacedObstacleBlownUp(), DataTypes.Position.Row, Bomberman.Player.Score, Bomberman.MovingEntity.SetGhost(), Bomberman.MovingEntity.Speed, and Bomberman.MovingEntity.timeToMove.
HandleKeys()
void Bomberman.Player.HandleKeys () inline private
Handles the keypresses
Definition at line 558 of file Player.cs.
         {
             foreach (var item in Controls)
             {
                 if (Input.GetKey(item.Key))
                 {
                     item.Value.Invoke();
                 }
             }
         }
References Bomberman.Player.Controls.
Referenced by Bomberman.Player.Update().
Kill()
override bool Bomberman.Player.Kill () inline virtual
Override the kill event so we can check for game over
Reimplemented from Bomberman.MovingEntity.
Definition at line 572 of file Player.cs.
         {
             if (Bonuses.ContainsKey(BonusType.Immunity))
             {
                 return false;
             }
             bool tookDamage = base.Kill();
             if (!this.Alive)
             {
                 PlayerDiedEventHandler?.Invoke(this, EventArgs.Empty);
             }
             else if (tookDamage)
             {
                 GameBoard.MenuController.RemoveHealth(this);
             }
             return tookDamage;
         }
References Bomberman.MovingEntity.Alive, Bomberman.Player.Bonuses, Bomberman.GameBoard.MenuController, and Menu.MenuController.RemoveHealth().
Referenced by Bomberman.Player.OnCollisionEnter2D().
ChangeName()
void Bomberman.Player.ChangeName (string newName) inline
Changes the player's name
Parameters
newName The new name of the player
Definition at line 597 of file Player.cs.
         {
             this.PlayerName = newName;
         }
References Bomberman.Player.PlayerName.
AddScore()
void Bomberman.Player.AddScore () inline
Increase the score of the player
Definition at line 605 of file Player.cs.
         {
             ++this.Score;
         }
References Bomberman.Player.Score.
Referenced by Bomberman.GameBoard.Update().
AllTheBombsPlaced()
bool Bomberman.Player.AllTheBombsPlaced () inline private
Check if all the bombs placed
Definition at line 613 of file Player.cs.
         {
             foreach (Bomb bomb in Bombs)
             {
                 if (!bomb.Placed)
                 {
                     return false;
                 }
             }
             return true;
         }
References Bomberman.Player.Bombs, and Bomberman.Bomb.Placed.
Referenced by Bomberman.Player.PlaceBomb().
Member Data Documentation
actionCooldown
float Bomberman.Player.actionCooldown = 0f private
Definition at line 19 of file Player.cs.
Referenced by Bomberman.Player.PlaceBomb(), Bomberman.Player.PlaceObstacle(), and Bomberman.Player.Update().
playerId
int Bomberman.Player.playerId private
Definition at line 23 of file Player.cs.
Referenced by Bomberman.Player.Awake(), and Bomberman.Player.PlaceObstacle().
playerName
string Bomberman.Player.playerName = "player" private
Definition at line 26 of file Player.cs.
bombPrefab
GameObject Bomberman.Player.bombPrefab private
Definition at line 34 of file Player.cs.
Referenced by Bomberman.Player.Init(), Bomberman.Player.LoadPlayer(), and Bomberman.Player.OnCollisionEnter2D().
PlayerDiedEventHandler
EventHandler Bomberman.Player.PlayerDiedEventHandler
Event to call when the player died
Definition at line 79 of file Player.cs.
spriteRenderer
SpriteRenderer Bomberman.Player.spriteRenderer private
The player's display
Definition at line 84 of file Player.cs.
Referenced by Bomberman.Player.Awake(), Bomberman.Player.OnCollisionEnter2D(), and Bomberman.Player.Update().
Property Documentation
PlayerName
string Bomberman.Player.PlayerName get private set
The player's name
Definition at line 31 of file Player.cs.
 { get => playerName; private set => playerName = value; }
Referenced by Bomberman.Player.ChangeName(), Persistance.PlayerSave.SavePlayer(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
Bonuses
Dictionary<BonusType, Bonus> Bomberman.Player.Bonuses = new Dictionary<BonusType, Bonus>() get private set
The bonuses active for the player
Definition at line 39 of file Player.cs.
 { get; private set; } = new Dictionary<BonusType, Bonus>();
Referenced by Menu.MenuController.AddBonus(), Bomberman.Player.Init(), Bomberman.Player.Kill(), Bomberman.Player.LoadPlayer(), Bomberman.Player.OnCollisionEnter2D(), Bomberman.Player.PlaceBomb(), Bomberman.Player.PlaceObstacle(), and Bomberman.Player.Update().
Controls
Dictionary<KeyCode, Action> Bomberman.Player.Controls = new Dictionary<KeyCode, Action>() get private set
The control's for the player
Definition at line 44 of file Player.cs.
 { get; private set; } = new Dictionary<KeyCode, Action>();
Referenced by Bomberman.Player.Awake(), and Bomberman.Player.HandleKeys().
Bombs
List<Bomb> Bomberman.Player.Bombs = new List<Bomb>() get private set
The bomb's of the player
Definition at line 49 of file Player.cs.
 { get; private set; } = new List<Bomb>();
Referenced by Bomberman.Player.AllTheBombsPlaced(), Bomberman.Player.Init(), Bomberman.Player.LoadPlayer(), Bomberman.Player.OnCollisionEnter2D(), and Bomberman.Player.PlaceBomb().
Score
int Bomberman.Player.Score = 0 get private set
The current score of the player
Definition at line 54 of file Player.cs.
 { get; private set; } = 0;
Referenced by Bomberman.Player.AddScore(), Bomberman.Player.LoadPlayer(), Persistance.PlayerSave.SavePlayer(), and Menu.PlayerInGameMenuHandler.SetUpPanel().
PlayerId
int Bomberman.Player.PlayerId get
The id of the player
Definition at line 59 of file Player.cs.
 { get => playerId; }
Referenced by Menu.MenuController.AddBonus(), Menu.MenuController.RemoveBonus(), Menu.MenuController.RemoveHealth(), and Persistance.PlayerSave.SavePlayer().
AvailableObstacle
int Bomberman.Player.AvailableObstacle = 0 get private set
How much placeable obstacle does the player has
Definition at line 64 of file Player.cs.
 { get; private set; } = 0;
Referenced by Bomberman.Player.LoadPlayer(), Bomberman.Player.OnCollisionEnter2D(), Bomberman.Player.PlacedObstacleBlownUp(), Bomberman.Player.PlaceObstacle(), and Persistance.PlayerSave.SavePlayer().
ImmunityMaxDuration
float Bomberman.Player.ImmunityMaxDuration get private set
The max duration of the players immunity
Definition at line 69 of file Player.cs.
 { get; private set; }
Referenced by Bomberman.Player.LoadPlayer(), Bomberman.Player.OnCollisionEnter2D(), Persistance.PlayerSave.SavePlayer(), and Bomberman.Player.Update().
GhostMaxDuration
float Bomberman.Player.GhostMaxDuration get private set
The max duration of how much time the player can be a ghost
Definition at line 74 of file Player.cs.
 { get; private set; }
Referenced by Bomberman.Player.LoadPlayer(), Bomberman.Player.OnCollisionEnter2D(), Persistance.PlayerSave.SavePlayer(), and Bomberman.Player.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/Player.cs