Bomberman: Bomberman.StalkerBrain Class Reference
Bomberman.StalkerBrain Class Reference
The stalker monster's brain
Public Member Functions
override void InitBrain (Monster body, float accuracy=0.9F)
Inits the brain
override Direction ChangedCell ()
What direction to move towards when changed cells
Private Member Functions
Direction NearestPlayerDir ()
Gets what direction to move to get to the nearest player
Private Attributes
PathFindingInterface pathFinder
Additional Inherited Members
Protected Member Functions inherited from Bomberman.MonsterBrain
Direction NextTargetDir ()
Gets the next target direction
Protected Attributes inherited from Bomberman.MonsterBrain
Monster body
The monster which the brain is controlling
Properties inherited from Bomberman.MonsterBrain
float Accuracy [get, private set]
The accuracy of the monster (how frequently should it be full random)
Detailed Description
The stalker monster's brain
Definition at line 11 of file StalkerBrain.cs.
Member Function Documentation
InitBrain()
override void Bomberman.StalkerBrain.InitBrain (Monster body, float accuracy = 0.9F) inline virtual
Inits the brain
Parameters
body The parent monster
accuracy The accuracy of the brain
Reimplemented from Bomberman.MonsterBrain.
Definition at line 20 of file StalkerBrain.cs.
         {
             base.InitBrain(body, accuracy);
             this.pathFinder = new BFS(body.GameBoard.Cells);
         }
References Bomberman.MonsterBrain.body, Bomberman.GameBoard.Cells, and Bomberman.MapEntity.GameBoard.
NearestPlayerDir()
Direction Bomberman.StalkerBrain.NearestPlayerDir () inline private
Gets what direction to move to get to the nearest player
Definition at line 29 of file StalkerBrain.cs.
         {
             //Get the path to the player
             Stack<BFSCell> path = pathFinder.GetPathToSearched(this.body.CurrentBoardPos, this.body.GameBoard.Players.Where(x => x.Alive).Select(x => x.CurrentBoardPos));
             //If there is no path
             if (path is null || path.Count == 0)
             {
                 return NextTargetDir();
             }
             else
             {
                 //Get the direction
                 BFSCell newTarget = path.Pop();
                 if (newTarget.Row == this.body.CurrentBoardPos.Row)
                 {
                     if (newTarget.Col == this.body.CurrentBoardPos.Col + 1)
                     {
                         return Direction.Right;
                     }
                     else
                     {
                         return Direction.Left;
                     }
                 }
                 else
                 {
                     if (newTarget.Row == this.body.CurrentBoardPos.Row + 1)
                     {
                         return Direction.Down;
                     }
                     else
                     {
                         return Direction.Up;
                     }
                 }
             }
         }
References Bomberman.MonsterBrain.body, PathFinding.BFSCell.Col, Bomberman.MapEntity.CurrentBoardPos, PathFinding.PathFindingInterface.GetPathToSearched(), Bomberman.MonsterBrain.NextTargetDir(), Bomberman.StalkerBrain.pathFinder, and PathFinding.BFSCell.Row.
Referenced by Bomberman.StalkerBrain.ChangedCell().
ChangedCell()
override Direction Bomberman.StalkerBrain.ChangedCell () inline virtual
What direction to move towards when changed cells
Returns
A new direction to move towards
Implements Bomberman.MonsterBrain.
Definition at line 71 of file StalkerBrain.cs.
         {
             if (Accuracy < Config.RND.NextDouble())
             {
                 return NextTargetDir();
             }
             else
             {
                 if (!body.DirectionPassable(body.CurrentDirection))
                 {
                     if (Config.RND.NextDouble() < Config.STALKERMISSCHANCE)
                     {
                         return NextTargetDir();
                     }
                     else
                     {
                         return NearestPlayerDir();
                     }
                 }
                 //Check if it is a juncktion if it is move towards the nearest player
                 else
                 {
                     List<Direction> possDir = new List<Direction>();
                     for (int i = 0; i < 4; i++)
                     {
                         if (body.DirectionPassable((Direction)i))
{
                             possDir.Add((Direction)i);
                         }
                     }
                     if (possDir.Count == 0)
                     {
                         return Direction.Left;
                     }
                     else if (possDir.Count == 1)
                     {
                         return possDir.First();
                     }
                     else if (possDir.Contains(this.body.CurrentDirection) && possDir.Count == 2)
                     {
                         return body.CurrentDirection;
                     }
                     else
                     {
                         return NearestPlayerDir();
                     }
                 }
             }
         }
References Bomberman.MonsterBrain.Accuracy, Bomberman.MonsterBrain.body, Bomberman.MovingEntity.CurrentDirection, Bomberman.MovingEntity.DirectionPassable(), Bomberman.StalkerBrain.NearestPlayerDir(), Bomberman.MonsterBrain.NextTargetDir(), Bomberman.Config.RND, and Bomberman.Config.STALKERMISSCHANCE.
Member Data Documentation
pathFinder
PathFindingInterface Bomberman.StalkerBrain.pathFinder private
Definition at line 13 of file StalkerBrain.cs.
Referenced by Bomberman.StalkerBrain.NearestPlayerDir().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/StalkerBrain.cs