Bomberman: Bomberman.Bonus Class Reference
Bomberman.Bonus Class Reference
Contains the methods and datas of the bonuses
Public Member Functions
void Show ()
If this is called, the bonus will be shown on the gameboard
void Hide ()
If this is called, the bonus will be hidden on the gameboard
override void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Initialize the bonus
void LoadBonus (BonusSave bonusSave)
Loads the bonus's paramenters
bool DecreaseDuration (float amount)
Decrease it's duration if it's duration hit's 0 or less return true
void ResetDecayingBonus (float baseDuration)
Resets the decaying type bonus duration to base duration (helpfull when a decaying bonus picked up when its already active)
bool IncreaseTier ()
Increases the tier of thee bonus
Properties
int Tier [get, private set]
The bonus's tier property
BonusType Type [get, private set]
The type of the bonus
float Duration [get, private set]
How much the bonus is active
bool Decaying [get, private set]
Is the bonus is decaying type or not
Properties inherited from Bomberman.MapEntity
Position CurrentBoardPos [get, protected set]
The entity's current position on the Board's grid
MapEntityType EntityType [get, protected set]
The type of the entity
GameBoard GameBoard [get, protected set]
Reference to the parent board
Private Attributes
int tier
BonusType type
float duration
bool decaying = false
Detailed Description
Contains the methods and datas of the bonuses
Definition at line 10 of file Bonus.cs.
Member Function Documentation
Show()
void Bomberman.Bonus.Show () inline
If this is called, the bonus will be shown on the gameboard
Definition at line 47 of file Bonus.cs.
         {
             this.gameObject.SetActive(true);
         }
Referenced by Bomberman.Obstacle.DropBonus(), and Bomberman.Obstacle.SpawnBonus().
Hide()
void Bomberman.Bonus.Hide () inline
If this is called, the bonus will be hidden on the gameboard
Definition at line 55 of file Bonus.cs.
         {
             this.gameObject.SetActive(false);
         }
Referenced by Bomberman.Player.OnCollisionEnter2D().
Init()
override void Bomberman.Bonus.Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos) inline virtual
Initialize the bonus
Reimplemented from Bomberman.MapEntity.
Definition at line 63 of file Bonus.cs.
         {
             base.Init(entityType, gameBoard, CurrentPos);
             this.GameBoard.Entites.Add(this);
         }
References Bomberman.GameBoard.Entites.
Referenced by Bomberman.Player.LoadPlayer(), Bomberman.Obstacle.ObstacleLoad(), Bomberman.Obstacle.Place(), and Bomberman.Obstacle.SpawnBonus().
LoadBonus()
void Bomberman.Bonus.LoadBonus (BonusSave bonusSave) inline
Loads the bonus's paramenters
Parameters
bonusSave The bonus to load
Definition at line 73 of file Bonus.cs.
         {
             this.Tier = bonusSave.Tier;
             this.Duration = bonusSave.Duration;
         }
References Bomberman.Bonus.Duration, Persistance.BonusSave.Duration, Bomberman.Bonus.Tier, and Persistance.BonusSave.Tier.
Referenced by Bomberman.Player.LoadPlayer().
DecreaseDuration()
bool Bomberman.Bonus.DecreaseDuration (float amount) inline
Decrease it's duration if it's duration hit's 0 or less return true
Parameters
amount How much to decrease
Returns
Exceptions
System.Exception
Definition at line 85 of file Bonus.cs.
         {
             if (!Decaying)
             {
                 throw new System.Exception("Not decaying");
             }
             this.Duration -= amount;
             return this.Duration <= 0;
         }
References Bomberman.Bonus.Decaying, and Bomberman.Bonus.Duration.
Referenced by Bomberman.Player.Update().
ResetDecayingBonus()
void Bomberman.Bonus.ResetDecayingBonus (float baseDuration) inline
Resets the decaying type bonus duration to base duration (helpfull when a decaying bonus picked up when its already active)
Definition at line 97 of file Bonus.cs.
         {
             this.Duration = baseDuration;
         }
References Bomberman.Bonus.Duration.
IncreaseTier()
bool Bomberman.Bonus.IncreaseTier () inline
Increases the tier of thee bonus
Definition at line 104 of file Bonus.cs.
         {
             int maxTier = 1;
             switch (Type)
             {
                 case BonusType.BonusBomb:
                     maxTier = BonusConfigs.EXTRA_BOMB_MAX_TIER;
                     break;
                 case BonusType.BombRange:
                     maxTier = BonusConfigs.EXTRA_RANGE_MAX_TIER;
                     break;
                 case BonusType.Detonator:
                     break;
                 case BonusType.Skate:
                     break;
                 case BonusType.Immunity:
                     break;
                 case BonusType.Ghost:
                     break;
                 case BonusType.Obstacle:
                     maxTier = BonusConfigs.OBSTACLE_BONUS_MAX_TIER;
                     break;
                 default:
                     break;
             }
             if (Tier < maxTier)
             {
                 Tier++;
                 return true;
             }
             return false;
         }
References DataTypes.BonusConfigs.EXTRA_BOMB_MAX_TIER, DataTypes.BonusConfigs.EXTRA_RANGE_MAX_TIER, DataTypes.BonusConfigs.OBSTACLE_BONUS_MAX_TIER, Bomberman.Bonus.Tier, and Bomberman.Bonus.Type.
Member Data Documentation
tier
int Bomberman.Bonus.tier private
Definition at line 13 of file Bonus.cs.
type
BonusType Bomberman.Bonus.type private
Definition at line 16 of file Bonus.cs.
duration
float Bomberman.Bonus.duration private
Definition at line 19 of file Bonus.cs.
decaying
bool Bomberman.Bonus.decaying = false private
Definition at line 22 of file Bonus.cs.
Property Documentation
Tier
int Bomberman.Bonus.Tier get private set
The bonus's tier property
Definition at line 27 of file Bonus.cs.
 { get => tier; private set => tier = value; }
Referenced by Bomberman.Bonus.IncreaseTier(), Bomberman.Bonus.LoadBonus(), and Persistance.BonusSave.SaveBonus().
Type
BonusType Bomberman.Bonus.Type get private set
The type of the bonus
Definition at line 32 of file Bonus.cs.
 { get => type; private set => type = value; }
Referenced by Bomberman.Bonus.IncreaseTier(), Bomberman.Player.OnCollisionEnter2D(), Persistance.BonusSave.SaveBonus(), Persistance.ObstacleSave.SaveObstacle(), Bomberman.GameBoard.Start(), and Bomberman.Player.Update().
Duration
float Bomberman.Bonus.Duration get private set
How much the bonus is active
Definition at line 37 of file Bonus.cs.
 { get => duration; private set => duration = value; }
Referenced by Bomberman.Bonus.DecreaseDuration(), Bomberman.Bonus.LoadBonus(), Bomberman.Player.OnCollisionEnter2D(), Bomberman.Bonus.ResetDecayingBonus(), and Persistance.BonusSave.SaveBonus().
Decaying
bool Bomberman.Bonus.Decaying get private set
Is the bonus is decaying type or not
Definition at line 42 of file Bonus.cs.
 { get => decaying; private set => decaying = value; }
Referenced by Bomberman.Bonus.DecreaseDuration(), Bomberman.Player.OnCollisionEnter2D(), Persistance.BonusSave.SaveBonus(), and Bomberman.Player.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/Bonus.cs