Bomberman: Menu.SavesMenu Class Reference
Menu.SavesMenu Class Reference
Handles the saves display
Public Member Functions
void Show ()
Show the save menu
void Hide ()
Hides the save menu
void ButtonEvent (GameObject gameObjectClicked)
When the button is pressed
Private Member Functions
void ResetButtons ()
Reset the buttons
void AddButtons ()
Adds the buttons Only the latest 7 saves will be displayed
Private Attributes
string[] files
The saves which are currently on the device
UnityEngine.UI.Button buttonPrefab
A button prefab
List< UnityEngine.UI.Button > buttons = new List<UnityEngine.UI.Button>()
The save file buttons
Detailed Description
Handles the saves display
Definition at line 14 of file SavesMenu.cs.
Member Function Documentation
ResetButtons()
void Menu.SavesMenu.ResetButtons () inline private
Reset the buttons
Definition at line 35 of file SavesMenu.cs.
         {
             while (buttons.Count != 0)
             {
                 GameObject.Destroy(buttons[0].gameObject);
                 buttons.RemoveAt(0);
             }
         }
References Menu.SavesMenu.buttons.
Referenced by Menu.SavesMenu.AddButtons().
Show()
void Menu.SavesMenu.Show () inline
Show the save menu
Definition at line 47 of file SavesMenu.cs.
         {
             if (!Directory.Exists("gameSaves"))
             {
                 Directory.CreateDirectory("gameSaves");
             }
             files = Directory.GetFiles("gameSaves");
             this.gameObject.transform.parent.transform.parent.gameObject.SetActive(true);
             AddButtons();
         }
References Menu.SavesMenu.AddButtons(), and Menu.SavesMenu.files.
Hide()
void Menu.SavesMenu.Hide () inline
Hides the save menu
Definition at line 62 of file SavesMenu.cs.
         {
             this.gameObject.transform.parent.transform.parent.gameObject.SetActive(false);
         }
ButtonEvent()
void Menu.SavesMenu.ButtonEvent (GameObject gameObjectClicked) inline
When the button is pressed
Parameters
gameObjectClicked Which button was pressed
Definition at line 71 of file SavesMenu.cs.
         {
             int index = -1;
             for (int i = 0; i < buttons.Count; i++)
             {
                 if (buttons[i].gameObject == gameObjectClicked)
                 {
                     index = i; break;
                 }
             }
             MainMenuConfig.saveFilePath = buttons[index].GetComponentInChildren<TMPro.TMP_Text>().text;
             SceneManager.LoadSceneAsync("BombermanScene");
         }
References Menu.SavesMenu.buttons, and Menu.MainMenuConfig.saveFilePath.
AddButtons()
void Menu.SavesMenu.AddButtons () inline private
Adds the buttons Only the latest 7 saves will be displayed
Definition at line 92 of file SavesMenu.cs.
         {
             ResetButtons();
             foreach (var file in files.Skip(files.Length - 7))
             {
                 UnityEngine.UI.Button button = Instantiate(buttonPrefab, this.gameObject.transform).GetComponent<UnityEngine.UI.Button>();
                 button.GetComponentInChildren<TMPro.TMP_Text>().text = file;
                 button.gameObject.SetActive(true);
                 buttons.Add(button);
             }
         }
References Menu.SavesMenu.buttonPrefab, Menu.SavesMenu.buttons, Menu.SavesMenu.files, and Menu.SavesMenu.ResetButtons().
Referenced by Menu.SavesMenu.Show().
Member Data Documentation
files
string [] Menu.SavesMenu.files private
The saves which are currently on the device
Definition at line 19 of file SavesMenu.cs.
Referenced by Menu.SavesMenu.AddButtons(), and Menu.SavesMenu.Show().
buttonPrefab
UnityEngine.UI.Button Menu.SavesMenu.buttonPrefab private
A button prefab
Definition at line 25 of file SavesMenu.cs.
Referenced by Menu.SavesMenu.AddButtons().
buttons
List<UnityEngine.UI.Button> Menu.SavesMenu.buttons = new List<UnityEngine.UI.Button>() private
The save file buttons
Definition at line 30 of file SavesMenu.cs.
Referenced by Menu.SavesMenu.AddButtons(), Menu.SavesMenu.ButtonEvent(), and Menu.SavesMenu.ResetButtons().
The documentation for this class was generated from the following file:
Assets/Scripts/Menu/SavesMenu.cs