Bomberman: Persistance.GameSave Class Reference
Persistance.GameSave Class Reference
A container to save the gameboard
Public Member Functions
GameSave ()
Constructor for NewtonSoft
GameSave (GameBoard gameBoardToSave, Vector3 battleRoyaleCircle)
Creates a new GameSave
Public Attributes
ObstacleSave[] Cells
The cells of the gameboard
float GameOverTimer
How long till the game is over
float[] BattleRoyaleTimers
The timer for the battle royales
int BattleRoyaleTimerIndex
What battleRoyale index are we using
int RowCount
How many rows does the gameboard has
int ColCount
How many cols does the gameboard has
bool Paused
Is the gameboard paused
bool StartGameOverCounter
Is the countback started
bool BattleRoyaleMode
Is the battle royale enabled
int RequiredPoints
How many points are required for victory
List< PlayerSave > Players = new List<PlayerSave>()
The player in the game
List< MonsterSave > Monsters = new List<MonsterSave>()
The monsters in the game
List< BonusSave > droppedBonusSaves = new List<BonusSave>()
The displaying bonuses
Position BattleRoyaleCircle
How big is the battle royale circle currently
Detailed Description
A container to save the gameboard
Definition at line 13 of file GameSave.cs.
Constructor & Destructor Documentation
GameSave() [1/2]
Persistance.GameSave.GameSave () inline
Constructor for NewtonSoft
Definition at line 77 of file GameSave.cs.
         {
         }
GameSave() [2/2]
Persistance.GameSave.GameSave (GameBoard gameBoardToSave, Vector3 battleRoyaleCircle) inline
Creates a new GameSave
Parameters
gameBoardToSave The board to save
battleRoyaleCircle The current size of the battle royale circle
Definition at line 86 of file GameSave.cs.
         {
             this.GameOverTimer = gameBoardToSave.gameOverTimer;
             this.RowCount = gameBoardToSave.RowCount;
             this.ColCount = gameBoardToSave.ColCount;
             this.BattleRoyaleMode = MainMenuConfig.BattleRoyale;
             this.RequiredPoints = MainMenuConfig.RequiredPoint;
             this.Paused = gameBoardToSave.Paused;
             this.StartGameOverCounter = gameBoardToSave.StartGameOverCounter;
             this.BattleRoyaleTimerIndex = gameBoardToSave.BattleRoyaleTimerIndex;
             this.BattleRoyaleTimers = gameBoardToSave.BattleRoyaleTimers;
             //Save the monsters
             foreach (var monster in gameBoardToSave.Monsters)
             {
                 MonsterSave monsterSave = new MonsterSave();
                 monsterSave.SaveMonster(monster);
                 Monsters.Add(monsterSave);
             }
             //Save the players
             foreach (var player in gameBoardToSave.Players)
             {
                 PlayerSave playerSave = new PlayerSave();
                 playerSave.SavePlayer(player);
                 Players.Add(playerSave);
             }
             //Save the cells
             Cells = new ObstacleSave[RowCount * ColCount];
             for (int i = 0; i < RowCount; i++)
             {
                 for (int j = 0; j < ColCount; j++)
                 {
                     ObstacleSave obstacleSave = new ObstacleSave();
                     obstacleSave.SaveObstacle(gameBoardToSave.Cells[i, j]);
                     Cells[i * ColCount + j] = obstacleSave;
                 }
             }
             //Save the droped bonuses
             foreach (var item in gameBoardToSave.Entites)
             {
                 if (item != null && item.gameObject.activeSelf && item is Bonus)
                 {
                     BonusSave bonusSave = new BonusSave();
                     bonusSave.SaveBonus((Bonus)item);
                     droppedBonusSaves.Add(bonusSave);
                 }
             }
             BattleRoyaleCircle = new Position((int)battleRoyaleCircle.y, (int)battleRoyaleCircle.x);
         }
References Menu.MainMenuConfig.BattleRoyale, Persistance.GameSave.BattleRoyaleCircle, Bomberman.GameBoard.BattleRoyaleTimerIndex, Bomberman.GameBoard.BattleRoyaleTimers, Persistance.GameSave.Cells, Bomberman.GameBoard.ColCount, Persistance.GameSave.ColCount, Persistance.GameSave.droppedBonusSaves, Bomberman.GameBoard.gameOverTimer, Persistance.GameSave.Monsters, Bomberman.GameBoard.Paused, Persistance.GameSave.Players, Menu.MainMenuConfig.RequiredPoint, Bomberman.GameBoard.RowCount, Persistance.GameSave.RowCount, Persistance.BonusSave.SaveBonus(), Persistance.MonsterSave.SaveMonster(), Persistance.ObstacleSave.SaveObstacle(), Persistance.PlayerSave.SavePlayer(), and Bomberman.GameBoard.StartGameOverCounter.
Member Data Documentation
Cells
ObstacleSave [] Persistance.GameSave.Cells
The cells of the gameboard
Definition at line 18 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
GameOverTimer
float Persistance.GameSave.GameOverTimer
How long till the game is over
Definition at line 22 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
BattleRoyaleTimers
float [] Persistance.GameSave.BattleRoyaleTimers
The timer for the battle royales
Definition at line 26 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
BattleRoyaleTimerIndex
int Persistance.GameSave.BattleRoyaleTimerIndex
What battleRoyale index are we using
Definition at line 30 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
RowCount
int Persistance.GameSave.RowCount
How many rows does the gameboard has
Definition at line 34 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
ColCount
int Persistance.GameSave.ColCount
How many cols does the gameboard has
Definition at line 38 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
Paused
bool Persistance.GameSave.Paused
Is the gameboard paused
Definition at line 42 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
StartGameOverCounter
bool Persistance.GameSave.StartGameOverCounter
Is the countback started
Definition at line 46 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
BattleRoyaleMode
bool Persistance.GameSave.BattleRoyaleMode
Is the battle royale enabled
Definition at line 50 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
RequiredPoints
int Persistance.GameSave.RequiredPoints
How many points are required for victory
Definition at line 54 of file GameSave.cs.
Referenced by Bomberman.GameBoard.LoadState().
Players
List<PlayerSave> Persistance.GameSave.Players = new List<PlayerSave>()
The player in the game
Definition at line 58 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
Monsters
List<MonsterSave> Persistance.GameSave.Monsters = new List<MonsterSave>()
The monsters in the game
Definition at line 62 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
droppedBonusSaves
List<BonusSave> Persistance.GameSave.droppedBonusSaves = new List<BonusSave>()
The displaying bonuses
Definition at line 66 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave().
BattleRoyaleCircle
Position Persistance.GameSave.BattleRoyaleCircle
How big is the battle royale circle currently
Definition at line 71 of file GameSave.cs.
Referenced by Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
The documentation for this class was generated from the following file:
Assets/Scripts/Persistance/GameSave.cs