Bomberman: Persistance.PlayerSave Class Reference
Persistance.PlayerSave Class Reference
A container to save the players
Public Member Functions
void SavePlayer (Player playerToSave)
Saves the player
Public Attributes
int PlayerId
string PlayerName
The player's name
List< BombSave > Bombs = new List<BombSave>()
The bomb's of the player
List< BonusSave > Bonuses = new List<BonusSave>()
The bonuses active for the player
int Score = 0
The current score of the player
int AvailableObstacle = 0
How many Obstacle can the player can still place
float ImmunityMaxDuration
How long does the ImmunityBonus lasts
float GhostMaxDuration
How long does the GhostDuration lasts
Public Attributes inherited from Persistance.MovingEntitySave
float Speed
The spped of the saved entity
int Hp
How many extra health does the saved entity has
float ImmuneTime
The entity's immuneTime
bool Alive
Is the entity alive
Direction CurrentDirection
The current moving direction of the entity
Public Attributes inherited from Persistance.MapEntitySave
Position CurrentBoardPos
The entity's current position on the Board's grid
MapEntityType EntityType
The type of the entity
Properties
string SkinName [get, private set]
The name of the player's skin
Additional Inherited Members
Protected Member Functions inherited from Persistance.MovingEntitySave
void SaveMovingEntity (MovingEntity entity)
Saves the entity's MovingEntity compontents
Protected Member Functions inherited from Persistance.MapEntitySave
void Save (MapEntity mapEntity)
Saves the Mapentity
Detailed Description
A container to save the players
Definition at line 10 of file PlayerSave.cs.
Member Function Documentation
SavePlayer()
void Persistance.PlayerSave.SavePlayer (Player playerToSave) inline
Saves the player
Parameters
playerToSave
Definition at line 58 of file PlayerSave.cs.
         {
             this.PlayerId = playerToSave.PlayerId;
             this.PlayerName = playerToSave.PlayerName;
             this.Score = playerToSave.Score;
             this.AvailableObstacle = playerToSave.AvailableObstacle;
             this.ImmunityMaxDuration = playerToSave.ImmunityMaxDuration;
             this.GhostMaxDuration = playerToSave.GhostMaxDuration;
             this.SkinName = MainMenuConfig.PlayerSkins[this.PlayerId];
             //Save the bombs
             foreach (var bomb in playerToSave.Bombs)
             {
                 BombSave bombSave = new BombSave();
                 bombSave.SaveBomb(bomb);
                 Bombs.Add(bombSave);
             }
             //Save the bonuses
             foreach (var item in playerToSave.Bonuses)
             {
                 BonusSave bombSave = new BonusSave();
                 bombSave.SaveBonus(item.Value);
                 this.Bonuses.Add(bombSave);
             }
             //Save the MovingEntityComponent
             base.SaveMovingEntity(playerToSave);
         }
References Bomberman.Player.AvailableObstacle, Persistance.PlayerSave.Bombs, Bomberman.Player.GhostMaxDuration, Bomberman.Player.ImmunityMaxDuration, Bomberman.Player.PlayerId, Persistance.PlayerSave.PlayerId, Bomberman.Player.PlayerName, Menu.MainMenuConfig.PlayerSkins, Persistance.BombSave.SaveBomb(), Persistance.BonusSave.SaveBonus(), Bomberman.Player.Score, and Persistance.PlayerSave.SkinName.
Referenced by Persistance.GameSave.GameSave().
Member Data Documentation
PlayerId
int Persistance.PlayerSave.PlayerId
Definition at line 13 of file PlayerSave.cs.
Referenced by Persistance.PlayerSave.SavePlayer().
PlayerName
string Persistance.PlayerSave.PlayerName
The player's name
Definition at line 18 of file PlayerSave.cs.
Bombs
List<BombSave> Persistance.PlayerSave.Bombs = new List<BombSave>()
The bomb's of the player
Definition at line 23 of file PlayerSave.cs.
Referenced by Persistance.PlayerSave.SavePlayer().
Bonuses
List<BonusSave> Persistance.PlayerSave.Bonuses = new List<BonusSave>()
The bonuses active for the player
Definition at line 28 of file PlayerSave.cs.
Score
int Persistance.PlayerSave.Score = 0
The current score of the player
Definition at line 33 of file PlayerSave.cs.
AvailableObstacle
int Persistance.PlayerSave.AvailableObstacle = 0
How many Obstacle can the player can still place
Definition at line 38 of file PlayerSave.cs.
ImmunityMaxDuration
float Persistance.PlayerSave.ImmunityMaxDuration
How long does the ImmunityBonus lasts
Definition at line 43 of file PlayerSave.cs.
GhostMaxDuration
float Persistance.PlayerSave.GhostMaxDuration
How long does the GhostDuration lasts
Definition at line 47 of file PlayerSave.cs.
Property Documentation
SkinName
string Persistance.PlayerSave.SkinName get private set
The name of the player's skin
Definition at line 52 of file PlayerSave.cs.
 { get; private set; }
Referenced by Persistance.PlayerSave.SavePlayer().
The documentation for this class was generated from the following file:
Assets/Scripts/Persistance/PlayerSave.cs