Bomberman: Menu.MenuController Class Reference
Menu.MenuController Class Reference
Manages the in game UI
Public Member Functions
void NewGame (List< Player > players)
Call it when new game is started Resets the game UI
void RemoveHealth (Player player)
Remove a health icon from the player
void AddBonus (BonusType bonusType, Player player)
Adds a bonus icon to the player's ui display
void RemoveBonus (BonusType bonusType, Player player)
Removes a bonus icon to the player's ui display
Private Member Functions
void Start ()
Called on first frame
Private Attributes
RectTransform leftMenu
The game's UI left menu panel
RectTransform rightMenu
The game's UI right menu panel
RectTransform GameBoard
The gameboard's transform
PlayerInGameMenuHandler[] PlayerInGameMenuHandlers
Reference to the ingame menu controller
Detailed Description
Manages the in game UI
Definition at line 10 of file MenuController.cs.
Member Function Documentation
Start()
void Menu.MenuController.Start () inline private
Called on first frame
Definition at line 39 of file MenuController.cs.
         {
             //Cap the fps to 60
             Application.targetFrameRate = 60;
             QualitySettings.vSyncCount = 0;
         }
NewGame()
void Menu.MenuController.NewGame (List< Player > players) inline
Call it when new game is started Resets the game UI
Parameters
players The players of the game
Definition at line 51 of file MenuController.cs.
         {
             for (int i = 0; i < players.Count; i++)
             {
                 if (PlayerInGameMenuHandlers.Length < players.Count)
                 {
                     Debug.LogError("Not enough PlayerInGameMenuHandlers for the players");
                     continue;
                 }
                 PlayerInGameMenuHandlers[i].SetUpPanel(players[i]);
                 PlayerInGameMenuHandlers[i].gameObject.SetActive(true);
             }
             for (int i = players.Count; i < PlayerInGameMenuHandlers.Length; i++)
             {
                 PlayerInGameMenuHandlers[i].gameObject.SetActive(false);
             }
         }
References Menu.MenuController.PlayerInGameMenuHandlers, and Menu.PlayerInGameMenuHandler.SetUpPanel().
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
RemoveHealth()
void Menu.MenuController.RemoveHealth (Player player) inline
Remove a health icon from the player
Parameters
player The player whos health we want to remove
Definition at line 73 of file MenuController.cs.
         {
             PlayerInGameMenuHandlers[player.PlayerId].RemoveHealth();
         }
References Bomberman.Player.PlayerId, Menu.MenuController.PlayerInGameMenuHandlers, and Menu.PlayerInGameMenuHandler.RemoveHealth().
Referenced by Bomberman.Player.Kill().
AddBonus()
void Menu.MenuController.AddBonus (BonusType bonusType, Player player) inline
Adds a bonus icon to the player's ui display
Parameters
bonusType The type of the bonus
player Which player we want to add the bonus
Definition at line 83 of file MenuController.cs.
         {
             PlayerInGameMenuHandlers[player.PlayerId].AddBonus(bonusType, player.Bonuses[bonusType].GetComponent<SpriteRenderer>().sprite);
         }
References Menu.PlayerInGameMenuHandler.AddBonus(), Bomberman.Player.Bonuses, Bomberman.Player.PlayerId, and Menu.MenuController.PlayerInGameMenuHandlers.
Referenced by Bomberman.GameBoard.LoadState(), and Bomberman.Player.OnCollisionEnter2D().
RemoveBonus()
void Menu.MenuController.RemoveBonus (BonusType bonusType, Player player) inline
Removes a bonus icon to the player's ui display
Parameters
bonusType The type of the bonus
player Which player we want to remove the bonus from
Definition at line 92 of file MenuController.cs.
         {
             PlayerInGameMenuHandlers[player.PlayerId].RemoveBonus(bonusType);
         }
References Bomberman.Player.PlayerId, Menu.MenuController.PlayerInGameMenuHandlers, and Menu.PlayerInGameMenuHandler.RemoveBonus().
Referenced by Bomberman.Player.Update().
Member Data Documentation
leftMenu
RectTransform Menu.MenuController.leftMenu private
The game's UI left menu panel
Definition at line 16 of file MenuController.cs.
rightMenu
RectTransform Menu.MenuController.rightMenu private
The game's UI right menu panel
Definition at line 22 of file MenuController.cs.
GameBoard
RectTransform Menu.MenuController.GameBoard private
The gameboard's transform
Definition at line 28 of file MenuController.cs.
PlayerInGameMenuHandlers
PlayerInGameMenuHandler [] Menu.MenuController.PlayerInGameMenuHandlers private
Reference to the ingame menu controller
Definition at line 34 of file MenuController.cs.
Referenced by Menu.MenuController.AddBonus(), Menu.MenuController.NewGame(), Menu.MenuController.RemoveBonus(), and Menu.MenuController.RemoveHealth().
The documentation for this class was generated from the following file:
Assets/Scripts/Menu/MenuController.cs