Bomberman: Menu.ModalWindow Class Reference
Menu.ModalWindow Class Reference
Modal window controller
Public Member Functions
void Show ()
Display the modalwindow without modifying anything
void Show (string title, string content, Action onOkAction=null)
Displays the modalwindow which modified values Also this hides the cancel button
void Show (string title, string content, Action onOkAction=null, Action onCancelAction=null)
Displays the modalwindow which modified values
void Show (string title, string content, Action onOkAction=null, Action onCancelAction=null, int width=BASE_WIDTH, int height=BASE_HEIGHT)
Displays the modalwindow which modified values
void Show (string title, string content, Action onOkAction=null, string confirmButtonLabel="Ok")
Displays the modalwindow which modified values Also this hides the cancel button
void Hide ()
Hides the modalwindow
void Cancel ()
Cancels the modalwindow
void ConfirmButtonClick ()
Confirm button event
Private Attributes
TMP_Text ModalTitleText
The title of the modalwindow
TMP_Text ModalContentText
The content of the modalwindow
TMP_Text ConfirmButtonText
The confirm button's text
Button CancelButton
The cancel button
Action onOkAction
What to do when the ok button is pressed
Action onCancelAction
What to do when the modal is closed
Static Private Attributes
const int BASE_WIDTH = 310
The window's default width
const int BASE_HEIGHT = 200
The window's default height
Detailed Description
Modal window controller
Definition at line 11 of file ModalWindowScript.cs.
Member Function Documentation
Show() [1/5]
void Menu.ModalWindow.Show () inline
Display the modalwindow without modifying anything
Definition at line 60 of file ModalWindowScript.cs.
         {
             this.gameObject.SetActive(true);
             this.CancelButton.gameObject.SetActive(true);
         }
Referenced by Menu.ModalWindow.Show(), and Bomberman.GameBoard.Update().
Show() [2/5]
void Menu.ModalWindow.Show (string title, string content, Action onOkAction = null) inline
Displays the modalwindow which modified values Also this hides the cancel button
Parameters
title The title of the modalwindow
content The content of the modalwindow
onOkAction What to do when the ok action is pressed
Definition at line 76 of file ModalWindowScript.cs.
         {
             this.ModalTitleText.text = title;
             this.ModalContentText.text = content;
             this.onOkAction = onOkAction;
             Show();
             this.CancelButton.gameObject.SetActive(false);
         }
References Menu.ModalWindow.onOkAction, and Menu.ModalWindow.Show().
Show() [3/5]
void Menu.ModalWindow.Show (string title, string content, Action onOkAction = null, Action onCancelAction = null) inline
Displays the modalwindow which modified values
Parameters
title The title of the modalwindow
content The content of the modalwindow
onOkAction What to do when the ok action is pressed
onCancelAction What to do when the cancel action is pressed
Definition at line 93 of file ModalWindowScript.cs.
         {
             this.ModalTitleText.text = title;
             this.ModalContentText.text = content;
             this.onOkAction = onOkAction;
             this.onCancelAction = onCancelAction;
             Show();
         }
References Menu.ModalWindow.onCancelAction, Menu.ModalWindow.onOkAction, and Menu.ModalWindow.Show().
Show() [4/5]
void Menu.ModalWindow.Show (string title, string content, Action onOkAction = null, Action onCancelAction = null, int width = BASE_WIDTH, int height = BASE_HEIGHT) inline
Displays the modalwindow which modified values
Parameters
title The title of the modalwindow
content The content of the modalwindow
onOkAction What to do when the ok action is pressed
onCancelAction What to do when the cancel action is pressed
width The new width of the window
height The new height of the window
Definition at line 111 of file ModalWindowScript.cs.
         {
             this.ModalTitleText.text = title;
             this.ModalContentText.text = content;
             this.onOkAction = onOkAction;
             this.onCancelAction = onCancelAction;
             Show();
             this.gameObject.GetComponent<RectTransform>().sizeDelta = new Vector2(width, height);
         }
References Menu.ModalWindow.onCancelAction, Menu.ModalWindow.onOkAction, and Menu.ModalWindow.Show().
Show() [5/5]
void Menu.ModalWindow.Show (string title, string content, Action onOkAction = null, string confirmButtonLabel = "Ok") inline
Displays the modalwindow which modified values Also this hides the cancel button
Parameters
title The title of the modalwindow
content The content of the modalwindow
onOkAction What to do when the ok action is pressed
confirmButtonLabel Canges the confirm button's text
Definition at line 132 of file ModalWindowScript.cs.
         {
             this.ModalTitleText.text = title;
             this.ModalContentText.text = content;
             this.onOkAction = onOkAction;
             this.ConfirmButtonText.text = confirmButtonLabel;
             RectTransform confButtonRectTrans = ConfirmButtonText.transform.parent.GetComponent<RectTransform>();
             confButtonRectTrans.sizeDelta = new Vector2(confirmButtonLabel.Length * 12 + 30, confButtonRectTrans.sizeDelta.y);
             Show();
         }
References Menu.ModalWindow.ConfirmButtonText, Menu.ModalWindow.onOkAction, and Menu.ModalWindow.Show().
Hide()
void Menu.ModalWindow.Hide () inline
Hides the modalwindow
Definition at line 147 of file ModalWindowScript.cs.
         {
             this.gameObject.SetActive(false);
         }
Referenced by Menu.ModalWindow.Cancel(), and Menu.ModalWindow.ConfirmButtonClick().
Cancel()
void Menu.ModalWindow.Cancel () inline
Cancels the modalwindow
Definition at line 155 of file ModalWindowScript.cs.
         {
             if (onCancelAction is not null)
             {
                 onCancelAction();
             }
             Hide();
         }
References Menu.ModalWindow.Hide(), and Menu.ModalWindow.onCancelAction.
ConfirmButtonClick()
void Menu.ModalWindow.ConfirmButtonClick () inline
Confirm button event
Definition at line 168 of file ModalWindowScript.cs.
         {
             if (onOkAction is not null)
             {
                 onOkAction();
             }
             Hide();
         }
References Menu.ModalWindow.Hide(), and Menu.ModalWindow.onOkAction.
Member Data Documentation
BASE_WIDTH
const int Menu.ModalWindow.BASE_WIDTH = 310 static private
The window's default width
Definition at line 16 of file ModalWindowScript.cs.
BASE_HEIGHT
const int Menu.ModalWindow.BASE_HEIGHT = 200 static private
The window's default height
Definition at line 20 of file ModalWindowScript.cs.
ModalTitleText
TMP_Text Menu.ModalWindow.ModalTitleText private
The title of the modalwindow
Definition at line 26 of file ModalWindowScript.cs.
ModalContentText
TMP_Text Menu.ModalWindow.ModalContentText private
The content of the modalwindow
Definition at line 32 of file ModalWindowScript.cs.
ConfirmButtonText
TMP_Text Menu.ModalWindow.ConfirmButtonText private
The confirm button's text
Definition at line 38 of file ModalWindowScript.cs.
Referenced by Menu.ModalWindow.Show().
CancelButton
Button Menu.ModalWindow.CancelButton private
The cancel button
Definition at line 44 of file ModalWindowScript.cs.
onOkAction
Action Menu.ModalWindow.onOkAction private
What to do when the ok button is pressed
Definition at line 49 of file ModalWindowScript.cs.
Referenced by Menu.ModalWindow.ConfirmButtonClick(), and Menu.ModalWindow.Show().
onCancelAction
Action Menu.ModalWindow.onCancelAction private
What to do when the modal is closed
Definition at line 53 of file ModalWindowScript.cs.
Referenced by Menu.ModalWindow.Cancel(), and Menu.ModalWindow.Show().
The documentation for this class was generated from the following file:
Assets/Scripts/Menu/ModalWindowScript.cs