Bomberman: Bomberman.Monster Class Reference
Bomberman.Monster Class Reference
The monsters class which defines their behavior
Public Member Functions
override void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Inits the entity should be called right after creating the entity
void LoadMonster (MonsterSave monsterSave, GameBoard gameBoard)
Loads the monster
Public Member Functions inherited from Bomberman.MovingEntity
override void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Inits the entity should be called right after creating the entity
virtual bool Kill ()
Kills the entity if it isn't immune and have 0 Health kill it
void InstantKill ()
Instantly kill the entity it's health and immuneTime doesn't matter
bool DirectionPassable (Direction dir)
Checks if the given direction is passable for the entity
virtual void ChangedCell (int boardRow, int boardCol)
Called when an entity changed it's cell on the board
void SetGhost (bool newValue)
Called when we want to set this moving entity type to ghost or not ghost
Protected Member Functions
override bool Move (Direction dir)
Controls the movement of the monster
Protected Member Functions inherited from Bomberman.MovingEntity
void Update ()
Called every frame update
void ChangeDir (Direction dir)
Changes the direction of the entity
Properties
MonsterType Type [get, private set]
The type of the monster
Properties inherited from Bomberman.MovingEntity
float ImmuneTime = 0f [get, protected set]
float Speed [get, protected set]
Speed of the entity (how fast it will move on the board)
int Hp [get, protected set]
How many times can the entity be "killed"
bool Alive = true [get, protected set]
Is the entity alive
Direction CurrentDirection = Direction.Left [get, protected set]
The current moving direction of the entity
float moveProgress [get, private set]
How is the move progressing (0.0-1.0)
float timeToMove = 1f [get, protected set]
How long does the movement take
Properties inherited from Bomberman.MapEntity
Position CurrentBoardPos [get, protected set]
The entity's current position on the Board's grid
MapEntityType EntityType [get, protected set]
The type of the entity
GameBoard GameBoard [get, protected set]
Reference to the parent board
Private Member Functions
new void Update ()
The type of the monster
void ReachedTarget (object o, EventArgs args)
Event for when the monster reached the target, so it can change dir if needed
Private Attributes
MonsterType monsterType = MonsterType.Basic
MonsterBrain Brain
The type of the monster
Additional Inherited Members
Public Attributes inherited from Bomberman.MovingEntity
EventHandler ReachedTargetEvent
Event which is called when it changed tiles completely
Protected Attributes inherited from Bomberman.MovingEntity
Direction NewDirection = Direction.None
Detailed Description
The monsters class which defines their behavior
Definition at line 11 of file Monster.cs.
Member Function Documentation
Update()
new void Bomberman.Monster.Update () inline private
The type of the monster
Definition at line 29 of file Monster.cs.
         {
             if (!Alive || GameBoard.Paused)
             {
                 return;
             }
             //If it is enclosed from all 4 sides
             if (timeToMove * 2 < moveProgress && !DirectionPassable(CurrentDirection))
             {
                 base.ChangeDir(Brain.ChangedCell());
             }
             base.Update();
         }
References Bomberman.MovingEntity.Alive, Bomberman.Monster.Brain, Bomberman.MonsterBrain.ChangedCell(), Bomberman.MovingEntity.CurrentDirection, Bomberman.MovingEntity.DirectionPassable(), Bomberman.MovingEntity.moveProgress, Bomberman.GameBoard.Paused, and Bomberman.MovingEntity.timeToMove.
Init()
override void Bomberman.Monster.Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos) inline virtual
Inits the entity should be called right after creating the entity
Parameters
entityType The type of the entity
gameBoard The parent board
CurrentPos The current position of the entity
Reimplemented from Bomberman.MapEntity.
Definition at line 49 of file Monster.cs.
         {
             base.Init(entityType, gameBoard, CurrentPos);
             //Inits the appropiate brain for the monster
             switch (Type)
             {
                 case MonsterType.Basic:
                     this.Brain = new BasicBrain();
                     break;
                 case MonsterType.Ghost:
                     this.Brain = new GhostBrain();
                     break;
                 case MonsterType.Smarty:
                     this.Brain = new SmartyBrain();
                     break;
                 case MonsterType.Stalker:
                     this.Brain = new StalkerBrain();
                     break;
                 default:
                     break;
             }
             this.Brain.InitBrain(this, 0.9f);
             ReachedTargetEvent = ReachedTarget;
             base.ChangeDir(Brain.ChangedCell());
         }
References Bomberman.Monster.Brain, Bomberman.MonsterBrain.ChangedCell(), Bomberman.MonsterBrain.InitBrain(), Bomberman.Monster.ReachedTarget(), Bomberman.MovingEntity.ReachedTargetEvent, and Bomberman.Monster.Type.
Referenced by Bomberman.Monster.LoadMonster().
Move()
override bool Bomberman.Monster.Move (Direction dir) inline protected virtual
Controls the movement of the monster
Reimplemented from Bomberman.MovingEntity.
Definition at line 84 of file Monster.cs.
         {
             if (Type == MonsterType.Ghost)
             {
                 Position possibleDir = Position.CreateCopyAndMoveDir(this.CurrentBoardPos, this.CurrentDirection);
                 if (this.GameBoard.Cells[possibleDir.Row, possibleDir.Col].HasBomb)
                 {
                     return false;
                 }
             }
             return base.Move(dir);
         }
References Bomberman.GameBoard.Cells, DataTypes.Position.Col, DataTypes.Position.CreateCopyAndMoveDir(), Bomberman.MapEntity.CurrentBoardPos, Bomberman.MovingEntity.CurrentDirection, Bomberman.Obstacle.HasBomb, DataTypes.Position.Row, and Bomberman.Monster.Type.
LoadMonster()
void Bomberman.Monster.LoadMonster (MonsterSave monsterSave, GameBoard gameBoard) inline
Loads the monster
Parameters
monsterSave The saved monster data
Definition at line 102 of file Monster.cs.
         {
             this.Type = monsterSave.Type;
             this.Alive = monsterSave.Alive;
             this.CurrentDirection = monsterSave.CurrentDirection;
             Init(MapEntityType.Monster, gameBoard, monsterSave.CurrentBoardPos);
             //Kill it if it is already dead
             if (!monsterSave.Alive)
             {
                 this.InstantKill();
             }
         }
References Bomberman.MovingEntity.Alive, Persistance.MovingEntitySave.Alive, Persistance.MapEntitySave.CurrentBoardPos, Bomberman.MovingEntity.CurrentDirection, Persistance.MovingEntitySave.CurrentDirection, Bomberman.Monster.Init(), Bomberman.MovingEntity.InstantKill(), Bomberman.Monster.Type, and Persistance.MonsterSave.Type.
ReachedTarget()
void Bomberman.Monster.ReachedTarget (object o, EventArgs args) inline private
Event for when the monster reached the target, so it can change dir if needed
Definition at line 120 of file Monster.cs.
         {
             base.ChangeDir(Brain.ChangedCell());
         }
References Bomberman.Monster.Brain, and Bomberman.MonsterBrain.ChangedCell().
Referenced by Bomberman.Monster.Init().
Member Data Documentation
monsterType
MonsterType Bomberman.Monster.monsterType = MonsterType.Basic private
Definition at line 14 of file Monster.cs.
Brain
MonsterBrain Bomberman.Monster.Brain private
The type of the monster
Definition at line 24 of file Monster.cs.
Referenced by Bomberman.Monster.Init(), Bomberman.Monster.ReachedTarget(), and Bomberman.Monster.Update().
Property Documentation
Type
MonsterType Bomberman.Monster.Type get private set
The type of the monster
Definition at line 19 of file Monster.cs.
 { get => monsterType; private set => monsterType = value; }
Referenced by Bomberman.Monster.Init(), Bomberman.Monster.LoadMonster(), Bomberman.Monster.Move(), and Persistance.MonsterSave.SaveMonster().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/Monster.cs