Bomberman: PathFinding.BFS Class Reference
PathFinding.BFS Class Reference
Algoritm for bfs pathfinding
Public Member Functions
BFS (Obstacle[,] Cells)
Creates a new BFS class
Stack< BFSCell > GetPathToSearched (Position startingPos, IEnumerable< Position > targets)
Gets the path to the targets returns when it found one of the targets
Private Member Functions
void CreateSearchGrid ()
void ResetGrid ()
Resets the BFS search grid table
Private Attributes
Obstacle[,] Cells
BFSCell[,] SearchGrid
Detailed Description
Algoritm for bfs pathfinding
Definition at line 10 of file BFS.cs.
Constructor & Destructor Documentation
BFS()
PathFinding.BFS.BFS (Obstacle Cells[,]) inline
Creates a new BFS class
Parameters
Cells The gameboard's cells 2d array
Definition at line 36 of file BFS.cs.
         {
             this.Cells = Cells;
             CreateSearchGrid();
         }
References PathFinding.BFS.Cells, and PathFinding.BFS.CreateSearchGrid().
Member Function Documentation
CreateSearchGrid()
void PathFinding.BFS.CreateSearchGrid () inline private
Definition at line 19 of file BFS.cs.
         {
             SearchGrid = new BFSCell[Cells.GetLength(0), Cells.GetLength(1)];
             for (int i = 0; i < Cells.GetLength(0); i++)
             {
                 for (int j = 0; j < Cells.GetLength(1); j++)
                 {
                     if (!Cells[i, j].NotPassable)
                         SearchGrid[i, j] = new BFSCell(i, j);
                 }
             }
         }
References PathFinding.BFS.Cells, and PathFinding.BFS.SearchGrid.
Referenced by PathFinding.BFS.BFS().
ResetGrid()
void PathFinding.BFS.ResetGrid () inline private
Resets the BFS search grid table
Definition at line 45 of file BFS.cs.
         {
             for (int i = 0; i < SearchGrid.GetLength(0); i++)
             {
                 for (int j = 0; j < SearchGrid.GetLength(1); j++)
                 {
                     if (SearchGrid[i, j] is not null)
                     {
                         SearchGrid[i, j].Reset();
                     }
                 }
             }
         }
References PathFinding.BFSCell.Reset(), and PathFinding.BFS.SearchGrid.
Referenced by PathFinding.BFS.GetPathToSearched().
GetPathToSearched()
Stack<BFSCell> PathFinding.BFS.GetPathToSearched (Position startingPos, IEnumerable< Position > targets) inline
Gets the path to the targets returns when it found one of the targets
Parameters
startingPos The starting position of the algorithm
targets The targets for the algorithm
Returns
The path to one of the target
Implements PathFinding.PathFindingInterface.
Definition at line 65 of file BFS.cs.
         {
             //If the starting position is not valid return
             if (SearchGrid[startingPos.Row, startingPos.Col] is null)
             {
                 return null;
             }
             //Reset the search grid
             ResetGrid();
             Queue<BFSCell> whatToCheck = new Queue<BFSCell>();
             SearchGrid[startingPos.Row, startingPos.Col].Visit(0, null);
             whatToCheck.Enqueue(SearchGrid[startingPos.Row, startingPos.Col]);
             //While the bfs still got nodes to check
             while (whatToCheck.Count != 0)
             {
                 BFSCell currNode = whatToCheck.Dequeue();
                 //Check if we reached target
                 foreach (var target in targets)
                 {
                     if (currNode.Row == target.Row && currNode.Col == target.Col)
                     {
                         Stack<BFSCell> path = new Stack<BFSCell>();
                         //Put the path into the path stack
                         while (currNode.Parent is not null)
{
                             path.Push(currNode);
                             currNode = currNode.Parent;
                         }
                         return path;
                     }
                     //Check the neighbouring cells if it is a new cell put it in the queue
                     BFSCell temp = null;
                     if (currNode.Row > 0)
                     {
                         temp = SearchGrid[currNode.Row - 1, currNode.Col];
                         if (temp is not null && !Cells[temp.Row, temp.Col].Placed && temp.Step == -1)
{
                             temp.Visit(currNode.Step + 1, currNode);
                             whatToCheck.Enqueue(temp);
                         }
                     }
                     if (currNode.Col > 0)
                     {
                         temp = SearchGrid[currNode.Row, currNode.Col - 1];
                         if (temp is not null && !Cells[temp.Row, temp.Col].Placed && temp.Step == -1)
{
                             temp.Visit(currNode.Step + 1, currNode);
                             whatToCheck.Enqueue(temp);
                         }
                     }
                     if (currNode.Row < Cells.GetLength(0) - 1)
                     {
                         temp = SearchGrid[currNode.Row + 1, currNode.Col];
                         if (temp is not null && !Cells[temp.Row, temp.Col].Placed && temp.Step == -1)
{
                             temp.Visit(currNode.Step + 1, currNode);
                             whatToCheck.Enqueue(temp);
                         }
                     }
                     if (currNode.Col < Cells.GetLength(1) - 1)
                     {
                         temp = SearchGrid[currNode.Row, currNode.Col + 1];
                         if (temp is not null && !Cells[temp.Row, temp.Col].Placed && temp.Step == -1)
{
                             temp.Visit(currNode.Step + 1, currNode);
                             whatToCheck.Enqueue(temp);
                         }
                     }
                 }
             }
             return null;
         }
References PathFinding.BFS.Cells, DataTypes.Position.Col, PathFinding.BFSCell.Col, Bomberman.Obstacle.Placed, PathFinding.BFS.ResetGrid(), DataTypes.Position.Row, PathFinding.BFSCell.Row, PathFinding.BFS.SearchGrid, PathFinding.BFSCell.Step, and PathFinding.BFSCell.Visit().
Member Data Documentation
Cells
Obstacle [,] PathFinding.BFS.Cells private
Definition at line 13 of file BFS.cs.
Referenced by PathFinding.BFS.BFS(), PathFinding.BFS.CreateSearchGrid(), and PathFinding.BFS.GetPathToSearched().
SearchGrid
BFSCell [,] PathFinding.BFS.SearchGrid private
Definition at line 16 of file BFS.cs.
Referenced by PathFinding.BFS.CreateSearchGrid(), PathFinding.BFS.GetPathToSearched(), and PathFinding.BFS.ResetGrid().
The documentation for this class was generated from the following file:
Assets/Scripts/PathFinding/BFS.cs