Bomberman: Bomberman.GhostBrain Class Reference
Bomberman.GhostBrain Class Reference
The ghost monster's brain
Public Member Functions
override Direction ChangedCell ()
What direction to move towards when changed cells
Public Member Functions inherited from Bomberman.MonsterBrain
virtual void InitBrain (Monster body, float accuracy=0.9f)
Inits the brain
Private Member Functions
bool DirectionTotallyImpassable ()
Gets it the ghost is currently facing towards an outer wall
Private Attributes
bool prevWall = false
Obstacle obstacle
Additional Inherited Members
Protected Member Functions inherited from Bomberman.MonsterBrain
Direction NextTargetDir ()
Gets the next target direction
Protected Attributes inherited from Bomberman.MonsterBrain
Monster body
The monster which the brain is controlling
Properties inherited from Bomberman.MonsterBrain
float Accuracy [get, private set]
The accuracy of the monster (how frequently should it be full random)
Detailed Description
The ghost monster's brain
Definition at line 8 of file GhostBrain.cs.
Member Function Documentation
DirectionTotallyImpassable()
bool Bomberman.GhostBrain.DirectionTotallyImpassable () inline private
Gets it the ghost is currently facing towards an outer wall
Definition at line 18 of file GhostBrain.cs.
         {
             if (body.GameBoard.Cells[body.CurrentBoardPos.Row, body.CurrentBoardPos.Col].HasBomb)
             {
                 return true;
             }
             switch (body.CurrentDirection)
             {
                 case Direction.Left:
                     return body.GameBoard.Cells[body.CurrentBoardPos.Row, body.CurrentBoardPos.Col - 1].HasBomb || body.CurrentBoardPos.Col <= 1;
                 case Direction.Up:
                     return body.GameBoard.Cells[body.CurrentBoardPos.Row-1, body.CurrentBoardPos.Col ].HasBomb || body.CurrentBoardPos.Row <= 1;
                 case Direction.Right:
                     return body.GameBoard.Cells[body.CurrentBoardPos.Row, body.CurrentBoardPos.Col + 1].HasBomb || body.CurrentBoardPos.Col >= body.GameBoard.ColCount - 2;
                 case Direction.Down:
                     return body.GameBoard.Cells[body.CurrentBoardPos.Row+1, body.CurrentBoardPos.Col].HasBomb || body.CurrentBoardPos.Row >= body.GameBoard.RowCount - 2;
                 default:
                     return false;
             }
         }
References Bomberman.MonsterBrain.body, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.GameBoard.ColCount, Bomberman.MapEntity.CurrentBoardPos, Bomberman.MovingEntity.CurrentDirection, Bomberman.MapEntity.GameBoard, Bomberman.Obstacle.HasBomb, DataTypes.Position.Row, and Bomberman.GameBoard.RowCount.
Referenced by Bomberman.GhostBrain.ChangedCell().
ChangedCell()
override Direction Bomberman.GhostBrain.ChangedCell () inline virtual
What direction to move towards when changed cells
Returns
A new direction to move towards
Implements Bomberman.MonsterBrain.
Definition at line 49 of file GhostBrain.cs.
         {
             if (Accuracy < Config.RND.NextDouble())
             {
                 return NextTargetDir();
             }
             else
             {
                 if (!body.DirectionPassable(body.CurrentDirection))
                 {
                     //Determine if the ghost should go through the wall
                     if (!DirectionTotallyImpassable() && (prevWall || Config.RND.NextDouble() <= Config.GHOSTPASSTHROUGHCHANCE))
                     {
                         prevWall = true;
                         return body.CurrentDirection;
                     }
                     return NextTargetDir();
                 }
                 else
                 {
                     prevWall = false;
                     return body.CurrentDirection;
                 }
             }
         }
References Bomberman.MonsterBrain.Accuracy, Bomberman.MonsterBrain.body, Bomberman.MovingEntity.CurrentDirection, Bomberman.MovingEntity.DirectionPassable(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Bomberman.Config.GHOSTPASSTHROUGHCHANCE, Bomberman.MonsterBrain.NextTargetDir(), Bomberman.GhostBrain.prevWall, and Bomberman.Config.RND.
Member Data Documentation
prevWall
bool Bomberman.GhostBrain.prevWall = false private
Definition at line 10 of file GhostBrain.cs.
Referenced by Bomberman.GhostBrain.ChangedCell().
obstacle
Obstacle Bomberman.GhostBrain.obstacle private
Definition at line 11 of file GhostBrain.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Game/GhostBrain.cs