Bomberman: Menu.KeyBindScript Class Reference
Menu.KeyBindScript Class Reference
Handles the player's key assignments
Public Member Functions
void ChangeKey (GameObject clicked)
Changes the selected contor's key
void SaveKeys ()
Saves the keys to the PlayerPrefs
void ResetSettings ()
Reset the keys (need the player to save to take effect)
Private Member Functions
void Start ()
Runs on the first frame
void OnGUI ()
Handle the gui update
void UpdateLabels ()
Update the button's labes
Private Attributes
Dictionary< string, TextMeshProUGUI > buttons
Start is called before the first frame update
Dictionary< string, KeyCode > keys = new Dictionary<string, KeyCode>()
The keys which are binded to the buttons
TextMeshProUGUI up
Reference to the player1's buttons
TextMeshProUGUI down
TextMeshProUGUI right
TextMeshProUGUI left
TextMeshProUGUI place
TextMeshProUGUI placeingObstacle
TextMeshProUGUI up2
Reference to the player2's buttons
TextMeshProUGUI down2
TextMeshProUGUI right2
TextMeshProUGUI left2
TextMeshProUGUI place2
TextMeshProUGUI placeingObstacle2
TextMeshProUGUI up3
Reference to the player3's buttons
TextMeshProUGUI down3
TextMeshProUGUI right3
TextMeshProUGUI left3
TextMeshProUGUI place3
TextMeshProUGUI placeingObstacle3
GameObject currentKey
The currently pressed button
Color32 normal = new Color32(255, 255, 255, 255)
The normal color of the button's
Color32 selected = new Color32(114, 112, 112, 255)
The button's color when it is selected
Detailed Description
Handles the player's key assignments
Definition at line 14 of file KeyBindScript.cs.
Member Function Documentation
Start()
void Menu.KeyBindScript.Start () inline private
Runs on the first frame
Definition at line 64 of file KeyBindScript.cs.
         {
             for (int i = 0; i < 3; i++)
             {
                 keys.Add("UpButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("UpButton" + i, Config.PLAYERDEFAULTKEYS[i, 0].ToString())));
                 keys.Add("DownButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("DownButton" + i, Config.PLAYERDEFAULTKEYS[i, 1].ToString())));
                 keys.Add("RightButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("RightButton" + i, Config.PLAYERDEFAULTKEYS[i, 2].ToString())));
                 keys.Add("LeftButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("LeftButton" + i, Config.PLAYERDEFAULTKEYS[i, 3].ToString())));
                 keys.Add("PlacingBombButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("PlacingBombButton" + i, Config.PLAYERDEFAULTKEYS[i, 4].ToString())));
                 keys.Add("PlacingObstacleButton" + i, (KeyCode)System.Enum.Parse(typeof(KeyCode), PlayerPrefs.GetString("PlacingObstacleButton" + i, Config.PLAYERDEFAULTKEYS[i, 5].ToString())));
             }
             UpdateLabels();
         }
References Menu.KeyBindScript.keys, Bomberman.Config.PLAYERDEFAULTKEYS, and Menu.KeyBindScript.UpdateLabels().
OnGUI()
void Menu.KeyBindScript.OnGUI () inline private
Handle the gui update
Definition at line 85 of file KeyBindScript.cs.
         {
             if (currentKey != null)
             {
                 Event e = Event.current;
                 if (e.isKey)
                 {
                     keys[currentKey.name] = e.keyCode;
                     currentKey.transform.GetChild(0).GetComponent<TextMeshProUGUI>().text = e.keyCode.ToString();
                     currentKey.GetComponent<Image>().color = normal;
                     currentKey = null;
                 }
             }
         }
References Menu.KeyBindScript.currentKey, Menu.KeyBindScript.keys, and Menu.KeyBindScript.normal.
UpdateLabels()
void Menu.KeyBindScript.UpdateLabels () inline private
Update the button's labes
Definition at line 103 of file KeyBindScript.cs.
         {
             up.text = keys["UpButton0"].ToString();
             down.text = keys["DownButton0"].ToString();
             right.text = keys["RightButton0"].ToString();
             left.text = keys["LeftButton0"].ToString();
             place.text = keys["PlacingBombButton0"].ToString();
             placeingObstacle.text = keys["PlacingObstacleButton0"].ToString();
             up2.text = keys["UpButton1"].ToString();
             down2.text = keys["DownButton1"].ToString();
             right2.text = keys["RightButton1"].ToString();
             left2.text = keys["LeftButton1"].ToString();
             place2.text = keys["PlacingBombButton1"].ToString();
             placeingObstacle2.text = keys["PlacingObstacleButton1"].ToString();
             up3.text = keys["UpButton2"].ToString();
             down3.text = keys["DownButton2"].ToString();
             right3.text = keys["RightButton2"].ToString();
             left3.text = keys["LeftButton2"].ToString();
             place3.text = keys["PlacingBombButton2"].ToString();
             placeingObstacle3.text = keys["PlacingObstacleButton2"].ToString();
         }
References Menu.KeyBindScript.down, Menu.KeyBindScript.down2, Menu.KeyBindScript.down3, Menu.KeyBindScript.keys, Menu.KeyBindScript.left, Menu.KeyBindScript.left2, Menu.KeyBindScript.left3, Menu.KeyBindScript.place, Menu.KeyBindScript.place2, Menu.KeyBindScript.place3, Menu.KeyBindScript.placeingObstacle, Menu.KeyBindScript.placeingObstacle2, Menu.KeyBindScript.placeingObstacle3, Menu.KeyBindScript.right, Menu.KeyBindScript.right2, Menu.KeyBindScript.right3, Menu.KeyBindScript.up, Menu.KeyBindScript.up2, and Menu.KeyBindScript.up3.
Referenced by Menu.KeyBindScript.ResetSettings(), and Menu.KeyBindScript.Start().
ChangeKey()
void Menu.KeyBindScript.ChangeKey (GameObject clicked) inline
Changes the selected contor's key
Parameters
clicked Which control (button) to change
Definition at line 131 of file KeyBindScript.cs.
         {
             if (currentKey != null)
             {
                 currentKey.GetComponent<Image>().color = normal;
             }
             currentKey = clicked;
             currentKey.GetComponent<Image>().color = selected;
         }
References Menu.KeyBindScript.currentKey, Menu.KeyBindScript.normal, and Menu.KeyBindScript.selected.
SaveKeys()
void Menu.KeyBindScript.SaveKeys () inline
Saves the keys to the PlayerPrefs
Definition at line 145 of file KeyBindScript.cs.
         {
             foreach (var key in keys)
             {
                 PlayerPrefs.SetString(key.Key, key.Value.ToString());
             }
             PlayerPrefs.Save();
         }
References Menu.KeyBindScript.keys.
ResetSettings()
void Menu.KeyBindScript.ResetSettings () inline
Reset the keys (need the player to save to take effect)
Definition at line 157 of file KeyBindScript.cs.
         {
             for (int i = 0; i < 3; i++)
             {
                 keys["UpButton" + i] = Config.PLAYERDEFAULTKEYS[i, 0];
                 keys["DownButton" + i] = Config.PLAYERDEFAULTKEYS[i, 1];
                 keys["RightButton" + i] = Config.PLAYERDEFAULTKEYS[i, 2];
                 keys["LeftButton" + i] = Config.PLAYERDEFAULTKEYS[i, 3];
                 keys["PlacingBombButton" + i] = Config.PLAYERDEFAULTKEYS[i, 4];
                 keys["PlacingObstacleButton" + i] = Config.PLAYERDEFAULTKEYS[i, 5];
             }
             UpdateLabels();
         }
References Menu.KeyBindScript.keys, Bomberman.Config.PLAYERDEFAULTKEYS, and Menu.KeyBindScript.UpdateLabels().
Member Data Documentation
buttons
Dictionary<string, TextMeshProUGUI> Menu.KeyBindScript.buttons private
Start is called before the first frame update
Definition at line 20 of file KeyBindScript.cs.
keys
Dictionary<string, KeyCode> Menu.KeyBindScript.keys = new Dictionary<string, KeyCode>() private
The keys which are binded to the buttons
Definition at line 24 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.OnGUI(), Menu.KeyBindScript.ResetSettings(), Menu.KeyBindScript.SaveKeys(), Menu.KeyBindScript.Start(), and Menu.KeyBindScript.UpdateLabels().
up
TextMeshProUGUI Menu.KeyBindScript.up private
Reference to the player1's buttons
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
down
TextMeshProUGUI Menu.KeyBindScript.down private
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
right
TextMeshProUGUI Menu.KeyBindScript.right private
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
left
TextMeshProUGUI Menu.KeyBindScript.left private
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
place
TextMeshProUGUI Menu.KeyBindScript.place private
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
placeingObstacle
TextMeshProUGUI Menu.KeyBindScript.placeingObstacle private
Definition at line 31 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
up2
TextMeshProUGUI Menu.KeyBindScript.up2 private
Reference to the player2's buttons
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
down2
TextMeshProUGUI Menu.KeyBindScript.down2 private
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
right2
TextMeshProUGUI Menu.KeyBindScript.right2 private
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
left2
TextMeshProUGUI Menu.KeyBindScript.left2 private
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
place2
TextMeshProUGUI Menu.KeyBindScript.place2 private
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
placeingObstacle2
TextMeshProUGUI Menu.KeyBindScript.placeingObstacle2 private
Definition at line 38 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
up3
TextMeshProUGUI Menu.KeyBindScript.up3 private
Reference to the player3's buttons
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
down3
TextMeshProUGUI Menu.KeyBindScript.down3 private
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
right3
TextMeshProUGUI Menu.KeyBindScript.right3 private
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
left3
TextMeshProUGUI Menu.KeyBindScript.left3 private
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
place3
TextMeshProUGUI Menu.KeyBindScript.place3 private
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
placeingObstacle3
TextMeshProUGUI Menu.KeyBindScript.placeingObstacle3 private
Definition at line 45 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.UpdateLabels().
currentKey
GameObject Menu.KeyBindScript.currentKey private
The currently pressed button
Definition at line 50 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.ChangeKey(), and Menu.KeyBindScript.OnGUI().
normal
Color32 Menu.KeyBindScript.normal = new Color32(255, 255, 255, 255) private
The normal color of the button's
Definition at line 55 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.ChangeKey(), and Menu.KeyBindScript.OnGUI().
selected
Color32 Menu.KeyBindScript.selected = new Color32(114, 112, 112, 255) private
The button's color when it is selected
Definition at line 59 of file KeyBindScript.cs.
Referenced by Menu.KeyBindScript.ChangeKey().
The documentation for this class was generated from the following file:
Assets/Scripts/Menu/KeyBindScript.cs