Bomberman: Bomberman.GameBoard Class Reference
Bomberman.GameBoard Class Reference
Controls the game
Public Member Functions
void MakeMapLoadManual ()
If called the map loading will be handled manually
void CreateBoard (string mapLayoutResourcePath)
Creates a new board specified by the given file's layout
void Pause ()
Make the game paused
void Resume ()
Make the game unpaused
void CheckGameOverEvent (object obj, EventArgs args)
Check if the game over timer should be started
void BackToMainMenu ()
Change to the main menu scene
void ExitGame ()
Closes the game (the whole application)
void OverrideBattleRoyaleTimers (float[] newTimers, float newRate=Config.CIRCLE_DECREASE_RATE)
Overrides the battle royale timers for testing only
void ForceSpecificMobTypeOnLoad (MonsterType monsterType)
Make a monster type force loaded
void SpawnBomb (Position whereToSpawn, int radius=Config.BOMBDEFAULTEXPLOSIONRANGE, bool permament=false)
Spawn a bomb at the given position
void SpawnBonus (BonusType bonusType, Position pos)
Spawn a bonus at a specific coordinate
void StartNextGame ()
Start the next game
void SaveState (string saveId="gameSaves\\save1.json")
Saves the gameBoards state
void LoadState (string savePath)
Loads the game according to the file
Public Attributes
MenuController MenuController
Properties
float gameOverTimer = Config.GAME_OVER_TIMER [get, private set]
This is where the gameOverTimer stored
float[] BattleRoyaleTimers [get, private set]
The timers for the battle royale circle (even index stay, odd index decrease)
int BattleRoyaleTimerIndex = 0 [get, private set]
What index to use in the timers
Obstacle[,] Cells [get, private set]
The cells of the board
List< MapEntity > Entites = new List<MapEntity>() [get, private set]
List of the entities such as Bonuses, Bombs etc.
int RowCount [get, private set]
The number of rows of the board
int ColCount [get, private set]
The number of cols of the board
List< Player > Players = new List<Player>() [get, private set]
The players on the board (check for alive)
List< Monster > Monsters = new List<Monster>() [get, private set]
The players on the board (check for alive)
bool Paused = false [get, private set]
The game is paused
bool StartGameOverCounter = false [get, private set]
The game over counter is started
Private Member Functions
void Update ()
Called every frame
void Start ()
Start is called before the first frame update
void DecreaseCircle ()
Decreases the battle royale circle
void CountDown ()
Count down waiting and shringing time
Private Attributes
string mapAssetPath = ""
bool loadMapOnStartUp = true
GameObject indestructibleWallPrefab
GameObject destructibleWallPrefab
List< GameObject > playerPrefabs
List< GameObject > monsterPrefabs
ModalWindow modalWindow
GameObject CircleGameObject
Text BattleRoyaleTimerText
SavesMenu SavesMenu
MonsterType forceMonsterType = MonsterType.None
float circleDecreaseRate = Config.CIRCLE_DECREASE_RATE
Detailed Description
Controls the game
Definition at line 20 of file GameBoard.cs.
Member Function Documentation
Update()
void Bomberman.GameBoard.Update () inline private
Called every frame
Definition at line 122 of file GameBoard.cs.
         {
             if (Paused)
             {
                 return;
             }
             if (StartGameOverCounter)
             {
                 if (!Paused)
                 {
                     gameOverTimer -= Time.deltaTime;
                     if (gameOverTimer <= 0)
                     {
                         Pause();
                         Player winner = Players.Find(x => x.Alive);
                         string modalContent;
                         if (winner is not null)
{
                             winner.AddScore();
                             modalContent = $"{winner.PlayerName} won this round!";
                         }
                         else
{
                             modalContent = "The round was a draw";
                         }
                         if (winner?.Score >= MainMenuConfig.RequiredPoint)
{
                             modalWindow.Show("The game is over", $"{winner.PlayerName} won the game!", BackToMainMenu, "Back to main menu");
                         }
                         else
{
                             modalWindow.Show("Round is over!", modalContent, StartNextGame);
                         }
                     }
                 }
             }
             if (MainMenuConfig.BattleRoyale)
             {
                 if (BattleRoyaleTimerIndex < BattleRoyaleTimers.Length)
                 {
                     BattleRoyaleTimers[BattleRoyaleTimerIndex] -= Time.deltaTime;
                     if (BattleRoyaleTimers[BattleRoyaleTimerIndex] < 0)
                     {
                         BattleRoyaleTimerIndex++;
                     }
                     CountDown();
                     if (BattleRoyaleTimerIndex % 2 == 1)
                     {
                         DecreaseCircle();
                     }
                 }
                 else
                 {
                     DecreaseCircle();
                 }
             }
         }
References Bomberman.Player.AddScore(), Bomberman.GameBoard.BackToMainMenu(), Menu.MainMenuConfig.BattleRoyale, Bomberman.GameBoard.BattleRoyaleTimerIndex, Bomberman.GameBoard.BattleRoyaleTimers, Bomberman.GameBoard.CountDown(), Bomberman.GameBoard.DecreaseCircle(), Bomberman.GameBoard.gameOverTimer, Bomberman.GameBoard.modalWindow, Bomberman.GameBoard.Pause(), Bomberman.GameBoard.Paused, Bomberman.GameBoard.Players, Menu.MainMenuConfig.RequiredPoint, Menu.ModalWindow.Show(), Bomberman.GameBoard.StartGameOverCounter, and Bomberman.GameBoard.StartNextGame().
Start()
void Bomberman.GameBoard.Start () inline private
Start is called before the first frame update
Definition at line 187 of file GameBoard.cs.
         {
             if (CircleGameObject is null)
             {
                 throw new Exception("The battle royale circle object is not set");
             }
             if (BattleRoyaleTimerText is null)
             {
                 throw new Exception("The battle royale timer container object is not set");
             }
             BonusPrefabs = new Dictionary<BonusType, GameObject>();
             foreach (var item in destructibleWallPrefab.GetComponent<Obstacle>().bonusPrefabs)
             {
                 Bonus bonus = item.GetComponent<Bonus>();
                 BonusPrefabs.Add(bonus.Type, item);
             }
             StartNextGame();
         }
References Bomberman.GameBoard.BattleRoyaleTimerText, Bomberman.Obstacle.bonusPrefabs, Bomberman.GameBoard.CircleGameObject, Bomberman.GameBoard.destructibleWallPrefab, Bomberman.GameBoard.StartNextGame(), and Bomberman.Bonus.Type.
MakeMapLoadManual()
void Bomberman.GameBoard.MakeMapLoadManual () inline
If called the map loading will be handled manually
Definition at line 211 of file GameBoard.cs.
         {
             this.loadMapOnStartUp = false;
         }
CreateBoard()
void Bomberman.GameBoard.CreateBoard (string mapLayoutResourcePath) inline
Creates a new board specified by the given file's layout
Definition at line 219 of file GameBoard.cs.
         {
             //lines
             string[] fileLines = Resources.Load<TextAsset>(mapLayoutResourcePath).text.Trim('\n').Replace("\r", "").Split('\n');
             this.Cells = new Obstacle[fileLines.Length, fileLines[0].Split(Config.CSVDELIMITER).Length];
             this.RowCount = this.Cells.GetLength(0);
             this.ColCount = this.Cells.GetLength(1);
             List<Position> playerSpawns = new List<Position>();
             List<Position> monsterSpawns = new List<Position>();
             for (int i = 0; i < fileLines.Length; i++)
             {
                 string[] splitted = fileLines[i].Split(Config.CSVDELIMITER);
                 for (int j = 0; j < splitted.Length; j++)
                 {
                     Obstacle obstacle;
                     //Determine by the type what to spawn
                     switch ((MapCell)Convert.ToByte(splitted[j]))
                     {
                         case MapCell.Walkable:
                             obstacle = Instantiate(destructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                             obstacle.Init(MapEntityType.Obstacle, this, new Position(i, j));
                             break;
                         case MapCell.IndestructibleWall:
                             obstacle = Instantiate(indestructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                             obstacle.Init(MapEntityType.Obstacle, this, new Position(i, j));
                             obstacle.Place(false);
                             break;
                         case MapCell.DestructibleWall:
                             obstacle = Instantiate(destructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                             obstacle.Init(MapEntityType.Obstacle, this, new Position(i, j));
                             obstacle.Place(true);
                             break;
                         case MapCell.PlayerSpawn:
                             obstacle = Instantiate(destructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                             obstacle.Init(MapEntityType.Obstacle, this, new Position(i, j));
                             playerSpawns.Add(new Position(i, j));
                             break;
                         case MapCell.MonsterSpawn:
                             obstacle = Instantiate(destructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                             obstacle.Init(MapEntityType.Obstacle, this, new Position(i, j));
                             monsterSpawns.Add(new Position(i, j));
                             break;
                         default:
                             Debug.LogError("No such MapcellType which was in the file");
                             obstacle = null;
                             break;
                     }
                     //Set the object position's on the board
                     obstacle.gameObject.transform.localPosition = new Vector3(j * Config.CELLSIZE, -2.5f - i * Config.CELLSIZE, 1);
                     Cells[i, j] = obstacle;
                 }
             }
             //Spawns the player's in
             int counter = 0;
             while (playerSpawns.Count != 0 && counter < (MainMenuConfig.Player3 ? 3 : 2))
             {
                 int index = Config.RND.Next(0, playerSpawns.Count);
                 if (Players.Count <= counter)
                 {
                     Players.Add(Instantiate(playerPrefabs[counter], this.transform).GetComponent<Player>());
                 }
                 Players[counter].Init(MapEntityType.Player, this, playerSpawns[index]);
                 Players[counter].gameObject.transform.localPosition = new Vector3(playerSpawns[index].Col * Config.CELLSIZE, -2.5f - playerSpawns[index].Row * Config.CELLSIZE, 2);
                 Players[counter].ChangeName(MainMenuConfig.PlayerNames[counter]);
                 Players[counter].PlayerDiedEventHandler = CheckGameOverEvent;
                 Players[counter].gameObject.SetActive(true);
                 playerSpawns.RemoveAt(index);
                 ++counter;
             }
             //Error detection
             if (counter < (MainMenuConfig.Player3 ? 3 : 2))
             {
                 Debug.LogError("Invalid map, no place to spawn the players");
             }
             //Delete the monsters so they are still random
             while (Monsters.Count != 0)
             {
                 Destroy(Monsters[0].gameObject);
                 Monsters.RemoveAt(0);
             }
             //Spawns the monsters in
             counter = 0;
             while (monsterSpawns.Count != 0)
             {
                 int index = Config.RND.Next(0, monsterSpawns.Count);
                 if (Monsters.Count <= counter)
                 {
                     if (forceMonsterType == MonsterType.None)
                     {
                         Monsters.Add(Instantiate(monsterPrefabs[Config.RND.Next(0, monsterPrefabs.Count)], this.transform).GetComponent<Monster>());
                     }
                     else
                     {
                         Monsters.Add(Instantiate(monsterPrefabs[(int)forceMonsterType], this.transform).GetComponent<Monster>());
                     }
                 }
                 Monsters[counter].Init(MapEntityType.Monster, this, monsterSpawns[index]);
                 Monsters[counter].gameObject.transform.localPosition = new Vector3(monsterSpawns[index].Col * Config.CELLSIZE, -2.5f - monsterSpawns[index].Row * Config.CELLSIZE, 2);
                 monsterSpawns.RemoveAt(index);
                 ++counter;
             }
             this.MenuController.NewGame(Players);
         }
References Bomberman.GameBoard.Cells, Bomberman.Config.CELLSIZE, Bomberman.GameBoard.CheckGameOverEvent(), Bomberman.GameBoard.ColCount, Bomberman.Config.CSVDELIMITER, Bomberman.GameBoard.destructibleWallPrefab, Bomberman.GameBoard.forceMonsterType, Bomberman.GameBoard.indestructibleWallPrefab, Bomberman.Obstacle.Init(), Bomberman.GameBoard.monsterPrefabs, Bomberman.GameBoard.Monsters, Menu.MenuController.NewGame(), Bomberman.Obstacle.Place(), Menu.MainMenuConfig.Player3, Menu.MainMenuConfig.PlayerNames, Bomberman.GameBoard.playerPrefabs, Bomberman.GameBoard.Players, Bomberman.Config.RND, and Bomberman.GameBoard.RowCount.
Referenced by Bomberman.GameBoard.StartNextGame().
DecreaseCircle()
void Bomberman.GameBoard.DecreaseCircle () inline private
Decreases the battle royale circle
Definition at line 338 of file GameBoard.cs.
         {
             if (CircleGameObject.transform.localScale.x < 0)
             {
                 return;
             }
             Vector3 size = CircleGameObject.transform.localScale - Vector3.one * circleDecreaseRate * Time.deltaTime;
             size.z = 0;
             CircleGameObject.transform.localScale = size;
         }
References Bomberman.GameBoard.circleDecreaseRate, and Bomberman.GameBoard.CircleGameObject.
Referenced by Bomberman.GameBoard.Update().
CountDown()
void Bomberman.GameBoard.CountDown () inline private
Count down waiting and shringing time
Definition at line 353 of file GameBoard.cs.
         {
             Debug.Log("MainMenuConfig.BattleRoyale:" + MainMenuConfig.BattleRoyale);
             if (MainMenuConfig.BattleRoyale && BattleRoyaleTimerIndex < BattleRoyaleTimers.Length)
             {
                 DateTime datetime = new DateTime((int)(TimeSpan.TicksPerSecond * BattleRoyaleTimers[BattleRoyaleTimerIndex]));
                 BattleRoyaleTimerText.text = datetime.ToString("mm:ss");
             }
             else
             {
                 BattleRoyaleTimerText.text = "00:00";
             }
         }
References Menu.MainMenuConfig.BattleRoyale, Bomberman.GameBoard.BattleRoyaleTimerIndex, Bomberman.GameBoard.BattleRoyaleTimers, and Bomberman.GameBoard.BattleRoyaleTimerText.
Referenced by Bomberman.GameBoard.Update().
Pause()
void Bomberman.GameBoard.Pause () inline
Make the game paused
Definition at line 370 of file GameBoard.cs.
         {
             this.Paused = true;
         }
References Bomberman.GameBoard.Paused.
Referenced by Bomberman.GameBoard.Update().
Resume()
void Bomberman.GameBoard.Resume () inline
Make the game unpaused
Definition at line 378 of file GameBoard.cs.
         {
             if (gameOverTimer >= 0)
             {
                 this.Paused = false;
             }
         }
References Bomberman.GameBoard.gameOverTimer, and Bomberman.GameBoard.Paused.
Referenced by Bomberman.GameBoard.LoadState(), and Bomberman.GameBoard.StartNextGame().
CheckGameOverEvent()
void Bomberman.GameBoard.CheckGameOverEvent (object obj, EventArgs args) inline
Check if the game over timer should be started
Definition at line 389 of file GameBoard.cs.
         {
             if (Players.Count(x => x.Alive) == 1)
             {
                 StartGameOverCounter = true;
             }
         }
References Bomberman.GameBoard.Players, and Bomberman.GameBoard.StartGameOverCounter.
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
BackToMainMenu()
void Bomberman.GameBoard.BackToMainMenu () inline
Change to the main menu scene
Definition at line 400 of file GameBoard.cs.
         {
             SceneManager.LoadSceneAsync("MainMenuScene");
         }
Referenced by Bomberman.GameBoard.Update().
ExitGame()
void Bomberman.GameBoard.ExitGame () inline
Closes the game (the whole application)
Definition at line 408 of file GameBoard.cs.
         {
             Application.Quit();
         }
OverrideBattleRoyaleTimers()
void Bomberman.GameBoard.OverrideBattleRoyaleTimers (float[] newTimers, float newRate = Config.CIRCLE_DECREASE_RATE) inline
Overrides the battle royale timers for testing only
Parameters
newTimers The new timers to use
Definition at line 417 of file GameBoard.cs.
         {
             this.BattleRoyaleTimers = newTimers;
             circleDecreaseRate = newRate;
         }
References Bomberman.GameBoard.BattleRoyaleTimers, and Bomberman.GameBoard.circleDecreaseRate.
ForceSpecificMobTypeOnLoad()
void Bomberman.GameBoard.ForceSpecificMobTypeOnLoad (MonsterType monsterType) inline
Make a monster type force loaded
Parameters
monsterType The type to force use (MonsterType.None) to reset it back to random
Definition at line 427 of file GameBoard.cs.
         {
             this.forceMonsterType = monsterType;
         }
SpawnBomb()
void Bomberman.GameBoard.SpawnBomb (Position whereToSpawn, int radius = Config.BOMBDEFAULTEXPLOSIONRANGE, bool permament = false) inline
Spawn a bomb at the given position
Parameters
whereToSpawn Where to spawn the bomb
Definition at line 436 of file GameBoard.cs.
         {
             Bomb bombToSpawn = Instantiate(Players[0].Bombs[0], this.transform).GetComponent<Bomb>();
             bombToSpawn.Init(MapEntityType.Bomb, this, whereToSpawn);
             this.Cells[whereToSpawn.Row, whereToSpawn.Col].PlaceBomb(bombToSpawn);
             bombToSpawn.PlaceByGameBoard(whereToSpawn, radius, permament);
         }
References Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.Init(), Bomberman.Obstacle.PlaceBomb(), Bomberman.Bomb.PlaceByGameBoard(), Bomberman.GameBoard.Players, and DataTypes.Position.Row.
SpawnBonus()
void Bomberman.GameBoard.SpawnBonus (BonusType bonusType, Position pos) inline
Spawn a bonus at a specific coordinate
Parameters
bonusType The type of the bonus
pos The position to spawn the bonus at
Definition at line 451 of file GameBoard.cs.
         {
             if (pos.Row >= 0 && pos.Col >= 0 && pos.Row < this.Cells.GetLength(0) && pos.Col < Cells.GetLength(1))
             {
                 this.Cells[pos.Row, pos.Col].SpawnBonus(bonusType);
             }
             else
             {
                 throw new IndexOutOfRangeException("The cells array is not big enough to spawn a bonus there!");
             }
         }
References Bomberman.GameBoard.Cells, DataTypes.Position.Col, DataTypes.Position.Row, and Bomberman.Obstacle.SpawnBonus().
Referenced by Bomberman.GameBoard.LoadState().
StartNextGame()
void Bomberman.GameBoard.StartNextGame () inline
Start the next game
Definition at line 466 of file GameBoard.cs.
         {
             if (MainMenuConfig.saveFilePath != "")
             {
                 LoadState(MainMenuConfig.saveFilePath);
             }
             else
             {
                 StartGameOverCounter = false;
                 gameOverTimer = Config.GAME_OVER_TIMER;
                 //Reset the battle royale components
                 CircleGameObject.SetActive(MainMenuConfig.BattleRoyale);
                 BattleRoyaleTimerText.transform.parent.gameObject.SetActive(MainMenuConfig.BattleRoyale);
                 BattleRoyaleTimers = Config.BATTLE_ROYALE_TIMERS.Select(x => x).ToArray();
                 BattleRoyaleTimerIndex = 0;
                 //Reset the battle royale circle
                 if (CircleGameObject is not null)
                 {
                     CircleGameObject.transform.localScale = new Vector3(1000, 1000);
                 }
                 if (Cells is not null)
                 {
                     //Cleare out the previous game's entities
                     for (int i = 0; i < Cells.GetLength(0); i++)
                     {
                         for (int j = 0; j < Cells.GetLength(1); j++)
{
                             Destroy(Cells[i, j].gameObject);
                         }
                     }
                     while (Entites.Count > 0)
                     {
                         if (Entites[0] != null)
{
                             Destroy(Entites[0].gameObject);
                         }
                         Entites.RemoveAt(0);
                     }
                 }
                 if (loadMapOnStartUp)
                 {
                     if (mapAssetPath != "")
                     {
                         CreateBoard(mapAssetPath);
                     }
                     else
                     {
                         //Not efficient, but can't do it other way
                         TextAsset[] maps = Resources.LoadAll<TextAsset>("Maps/GameMaps/");
                         CreateBoard("Maps/GameMaps/" + maps[Config.RND.Next(0, maps.Length)].name);
                     }
                     Resume();
                 }
             }
         }
References Bomberman.Config.BATTLE_ROYALE_TIMERS, Menu.MainMenuConfig.BattleRoyale, Bomberman.GameBoard.BattleRoyaleTimerIndex, Bomberman.GameBoard.BattleRoyaleTimers, Bomberman.GameBoard.BattleRoyaleTimerText, Bomberman.GameBoard.Cells, Bomberman.GameBoard.CircleGameObject, Bomberman.GameBoard.CreateBoard(), Bomberman.GameBoard.Entites, Bomberman.Config.GAME_OVER_TIMER, Bomberman.GameBoard.gameOverTimer, Bomberman.GameBoard.loadMapOnStartUp, Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.mapAssetPath, Bomberman.GameBoard.Resume(), Bomberman.Config.RND, Menu.MainMenuConfig.saveFilePath, and Bomberman.GameBoard.StartGameOverCounter.
Referenced by Bomberman.GameBoard.Start(), and Bomberman.GameBoard.Update().
SaveState()
void Bomberman.GameBoard.SaveState (string saveId = "gameSaves\\save1.json") inline
Saves the gameBoards state
Definition at line 526 of file GameBoard.cs.
         {
             if (!Directory.Exists("gameSaves"))
             {
                 Directory.CreateDirectory("gameSaves");
             }
             string[] files = Directory.GetFiles("gameSaves");
             if (saveId == "")
             {
                 saveId = "gameSaves/" + DateTime.Now.ToString("yyyy_MM_DD_HH_mm_ss") + ".json";
             }
             GameSave gameSave = new GameSave(this, CircleGameObject.transform.localScale);
             string jsonString = JsonConvert.SerializeObject(gameSave, formatting: Formatting.Indented);
             File.WriteAllText(saveId, jsonString);
         }
References Bomberman.GameBoard.CircleGameObject.
LoadState()
void Bomberman.GameBoard.LoadState (string savePath) inline
Loads the game according to the file
Parameters
savePath The path to the saveFile
Definition at line 548 of file GameBoard.cs.
         {
             string json = File.ReadAllText(savePath);
             //Load it
             GameSave gameSave = JsonConvert.DeserializeObject<GameSave>(json);
             //Change the gameboard's field and MenuConfig to match the save's fields
             this.gameOverTimer = gameSave.GameOverTimer;
             this.BattleRoyaleTimers = gameSave.BattleRoyaleTimers;
             this.BattleRoyaleTimerIndex = gameSave.BattleRoyaleTimerIndex;
             this.RowCount = gameSave.RowCount;
             this.ColCount = gameSave.ColCount;
             this.Paused = gameSave.Paused;
             this.StartGameOverCounter = gameSave.StartGameOverCounter;
             MainMenuConfig.BattleRoyale = gameSave.BattleRoyaleMode;
             MainMenuConfig.RequiredPoint = gameSave.RequiredPoints;
             CircleGameObject.SetActive(MainMenuConfig.BattleRoyale);
             BattleRoyaleTimerText.transform.parent.gameObject.SetActive(MainMenuConfig.BattleRoyale);
             //Change the battle royale circle's size
             if (CircleGameObject is not null)
             {
                 CircleGameObject.transform.localScale = new Vector3(gameSave.BattleRoyaleCircle.Col, gameSave.BattleRoyaleCircle.Row);
             }
             //Delete the old gameObjects
             if (Cells is not null)
             {
                 //Cleare out the previous game's entities
                 for (int i = 0; i < Cells.GetLength(0); i++)
                 {
                     for (int j = 0; j < Cells.GetLength(1); j++)
                     {
                         Destroy(Cells[i, j].gameObject);
                     }
                 }
                 while (Entites.Count > 0)
                 {
                     if (Entites[0] != null)
                     {
                         Destroy(Entites[0].gameObject);
                     }
                     Entites.RemoveAt(0);
                 }
             }
             //Load the game's state
             this.Cells = new Obstacle[RowCount, ColCount];
             //This is for the obstacle bonus
             Dictionary<int, List<Obstacle>> playerObstacles = new Dictionary<int, List<Obstacle>>();
             for (int i = 0; i < 3; i++)
             {
                 playerObstacles.Add(i, new List<Obstacle>());
             }
             //Create the cells
             for (int i = 0; i < RowCount; i++)
             {
                 for (int j = 0; j < ColCount; j++)
                 {
                     ObstacleSave obstacleSave = gameSave.Cells[i * RowCount + j];
                     Obstacle obstacle;
                     if (obstacleSave.NotPassable)
                     {
                         obstacle = Instantiate(indestructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                     }
                     else
                     {
                         obstacle = Instantiate(destructibleWallPrefab, this.gameObject.transform).GetComponent<Obstacle>();
                     }
                     obstacle.Init(MapEntityType.Obstacle, this, obstacleSave.CurrentBoardPos);
                     obstacle.gameObject.transform.localPosition = new Vector3(j * Config.CELLSIZE, -2.5f - i * Config.CELLSIZE, 1);
                     obstacle.ObstacleLoad(obstacleSave);
                     if (obstacleSave.OwnerId != -1)
                     {
                         playerObstacles[obstacleSave.OwnerId].Add(obstacle);
                     }
                     Cells[i, j] = obstacle;
                 }
             }
             //Load the players
             for (int i = 0; i < gameSave.Players.Count; i++)
             {
                 MainMenuConfig.PlayerNames[i] = gameSave.Players[i].SkinName;
                 MainMenuConfig.PlayerNames[i] = gameSave.Players[i].PlayerName;
                 if (Players.Count <= i)
                 {
                     Players.Add(Instantiate(playerPrefabs[i], this.transform).GetComponent<Player>());
                 }
                 Players[i].LoadPlayer(gameSave.Players[i], this, playerObstacles[i]);
                 Players[i].gameObject.transform.localPosition = new Vector3(gameSave.Players[i].CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - gameSave.Players[i].CurrentBoardPos.Row * Config.CELLSIZE, 2);
                 Players[i].PlayerDiedEventHandler = CheckGameOverEvent;
                 Players[i].gameObject.SetActive(true);
             }
             //Delete the monsters so they are still random
             while (Monsters.Count != 0)
             {
                 Destroy(Monsters[0].gameObject);
                 Monsters.RemoveAt(0);
             }
             //Load the monsters
             for (int i = 0; i < gameSave.Monsters.Count; i++)
             {
                 Monsters.Add(Instantiate(monsterPrefabs[(int)gameSave.Monsters[i].Type], this.transform).GetComponent<Monster>());
                 Monsters[i].gameObject.transform.localPosition = new Vector3(gameSave.Monsters[i].CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - gameSave.Monsters[i].CurrentBoardPos.Row * Config.CELLSIZE, 2);
                 Monsters[i].LoadMonster(gameSave.Monsters[i], this);
             }
             //And spawn the currently visible bonuses
             foreach (var item in gameSave.droppedBonusSaves)
             {
                 this.SpawnBonus(item.Type, item.CurrentBoardPos);
             }
             this.MenuController.NewGame(Players);
             //Update the in game menu to display the new gamestate
             foreach (var item in this.Players)
             {
                 foreach (var bonus in item.Bonuses)
                 {
                     MenuController.AddBonus(bonus.Key, item);
                 }
             }
             this.Resume();
             //Clear this load request
             MainMenuConfig.saveFilePath = "";
             //Check if it is a 3 player game
             MainMenuConfig.Player3 = gameSave.Players.Count == 3;
         }
References Menu.MenuController.AddBonus(), Menu.MainMenuConfig.BattleRoyale, Persistance.GameSave.BattleRoyaleCircle, Persistance.GameSave.BattleRoyaleMode, Bomberman.GameBoard.BattleRoyaleTimerIndex, Persistance.GameSave.BattleRoyaleTimerIndex, Bomberman.GameBoard.BattleRoyaleTimers, Persistance.GameSave.BattleRoyaleTimers, Bomberman.GameBoard.BattleRoyaleTimerText, Bomberman.GameBoard.Cells, Persistance.GameSave.Cells, Bomberman.Config.CELLSIZE, Bomberman.GameBoard.CheckGameOverEvent(), Bomberman.GameBoard.CircleGameObject, DataTypes.Position.Col, Bomberman.GameBoard.ColCount, Persistance.GameSave.ColCount, Persistance.MapEntitySave.CurrentBoardPos, Bomberman.GameBoard.destructibleWallPrefab, Bomberman.GameBoard.Entites, Bomberman.GameBoard.gameOverTimer, Persistance.GameSave.GameOverTimer, Bomberman.GameBoard.indestructibleWallPrefab, Bomberman.Obstacle.Init(), Bomberman.GameBoard.monsterPrefabs, Bomberman.GameBoard.Monsters, Persistance.GameSave.Monsters, Menu.MenuController.NewGame(), Persistance.ObstacleSave.NotPassable, Bomberman.Obstacle.ObstacleLoad(), Persistance.ObstacleSave.OwnerId, Bomberman.GameBoard.Paused, Persistance.GameSave.Paused, Menu.MainMenuConfig.Player3, Menu.MainMenuConfig.PlayerNames, Bomberman.GameBoard.playerPrefabs, Bomberman.GameBoard.Players, Persistance.GameSave.Players, Menu.MainMenuConfig.RequiredPoint, Persistance.GameSave.RequiredPoints, Bomberman.GameBoard.Resume(), DataTypes.Position.Row, Bomberman.GameBoard.RowCount, Persistance.GameSave.RowCount, Menu.MainMenuConfig.saveFilePath, Bomberman.GameBoard.SpawnBonus(), Bomberman.GameBoard.StartGameOverCounter, and Persistance.GameSave.StartGameOverCounter.
Referenced by Bomberman.GameBoard.StartNextGame().
Member Data Documentation
MenuController
MenuController Bomberman.GameBoard.MenuController
Definition at line 23 of file GameBoard.cs.
Referenced by Bomberman.Player.Kill(), Bomberman.Player.OnCollisionEnter2D(), and Bomberman.Player.Update().
mapAssetPath
string Bomberman.GameBoard.mapAssetPath = "" private
Definition at line 27 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.StartNextGame().
loadMapOnStartUp
bool Bomberman.GameBoard.loadMapOnStartUp = true private
Definition at line 30 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.StartNextGame().
indestructibleWallPrefab
GameObject Bomberman.GameBoard.indestructibleWallPrefab private
Definition at line 34 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
destructibleWallPrefab
GameObject Bomberman.GameBoard.destructibleWallPrefab private
Definition at line 37 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CreateBoard(), Bomberman.GameBoard.LoadState(), and Bomberman.GameBoard.Start().
playerPrefabs
List<GameObject> Bomberman.GameBoard.playerPrefabs private
Definition at line 40 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
monsterPrefabs
List<GameObject> Bomberman.GameBoard.monsterPrefabs private
Definition at line 43 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
modalWindow
ModalWindow Bomberman.GameBoard.modalWindow private
Definition at line 46 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.Update().
CircleGameObject
GameObject Bomberman.GameBoard.CircleGameObject private
Definition at line 49 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.DecreaseCircle(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.SaveState(), Bomberman.GameBoard.Start(), and Bomberman.GameBoard.StartNextGame().
BattleRoyaleTimerText
Text Bomberman.GameBoard.BattleRoyaleTimerText private
Definition at line 52 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CountDown(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.Start(), and Bomberman.GameBoard.StartNextGame().
SavesMenu
SavesMenu Bomberman.GameBoard.SavesMenu private
Definition at line 55 of file GameBoard.cs.
forceMonsterType
MonsterType Bomberman.GameBoard.forceMonsterType = MonsterType.None private
Definition at line 63 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.CreateBoard().
circleDecreaseRate
float Bomberman.GameBoard.circleDecreaseRate = Config.CIRCLE_DECREASE_RATE private
Definition at line 75 of file GameBoard.cs.
Referenced by Bomberman.GameBoard.DecreaseCircle(), and Bomberman.GameBoard.OverrideBattleRoyaleTimers().
Property Documentation
gameOverTimer
float Bomberman.GameBoard.gameOverTimer = Config.GAME_OVER_TIMER get private set
This is where the gameOverTimer stored
Definition at line 60 of file GameBoard.cs.
 { get; private set; } = Config.GAME_OVER_TIMER;
Referenced by Persistance.GameSave.GameSave(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.Resume(), Bomberman.GameBoard.StartNextGame(), and Bomberman.GameBoard.Update().
BattleRoyaleTimers
float [] Bomberman.GameBoard.BattleRoyaleTimers get private set
The timers for the battle royale circle (even index stay, odd index decrease)
Definition at line 68 of file GameBoard.cs.
 { get; private set; }
Referenced by Bomberman.GameBoard.CountDown(), Persistance.GameSave.GameSave(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.OverrideBattleRoyaleTimers(), Bomberman.GameBoard.StartNextGame(), and Bomberman.GameBoard.Update().
BattleRoyaleTimerIndex
int Bomberman.GameBoard.BattleRoyaleTimerIndex = 0 get private set
What index to use in the timers
Definition at line 73 of file GameBoard.cs.
 { get; private set; } = 0;
Referenced by Bomberman.GameBoard.CountDown(), Persistance.GameSave.GameSave(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.StartNextGame(), and Bomberman.GameBoard.Update().
Cells
Obstacle [,] Bomberman.GameBoard.Cells get private set
The cells of the board
Definition at line 80 of file GameBoard.cs.
 { get; private set; }
Referenced by Bomberman.Bomb.BlownUp(), Bomberman.GameBoard.CreateBoard(), Bomberman.MovingEntity.DirectionPassable(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Bomberman.Bomb.ExpandExplosion(), Bomberman.MovingEntity.GetNextTarget(), Bomberman.SmartyBrain.InitBrain(), Bomberman.StalkerBrain.InitBrain(), Bomberman.Bomb.LoadBomb(), Bomberman.GameBoard.LoadState(), Bomberman.Monster.Move(), Bomberman.Player.PlaceBomb(), Bomberman.Player.PlaceObstacle(), Bomberman.GameBoard.SpawnBomb(), Bomberman.GameBoard.SpawnBonus(), Bomberman.GameBoard.StartNextGame(), and Bomberman.Player.Update().
Entites
List<MapEntity> Bomberman.GameBoard.Entites = new List<MapEntity>() get private set
List of the entities such as Bonuses, Bombs etc.
Definition at line 85 of file GameBoard.cs.
 { get; private set; } = new List<MapEntity>();
Referenced by Bomberman.Bonus.Init(), Bomberman.GameBoard.LoadState(), Bomberman.Player.OnCollisionEnter2D(), and Bomberman.GameBoard.StartNextGame().
RowCount
int Bomberman.GameBoard.RowCount get private set
The number of rows of the board
Definition at line 90 of file GameBoard.cs.
 { get; private set; }
Referenced by Bomberman.GameBoard.CreateBoard(), Bomberman.MovingEntity.DirectionPassable(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
ColCount
int Bomberman.GameBoard.ColCount get private set
The number of cols of the board
Definition at line 95 of file GameBoard.cs.
 { get; private set; }
Referenced by Bomberman.GameBoard.CreateBoard(), Bomberman.MovingEntity.DirectionPassable(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Persistance.GameSave.GameSave(), and Bomberman.GameBoard.LoadState().
Players
List<Player> Bomberman.GameBoard.Players = new List<Player>() get private set
The players on the board (check for alive)
Definition at line 100 of file GameBoard.cs.
 { get; private set; } = new List<Player>();
Referenced by Bomberman.Bomb.BlowUp(), Bomberman.GameBoard.CheckGameOverEvent(), Bomberman.GameBoard.CreateBoard(), Bomberman.Bomb.ExpandExplosion(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.SpawnBomb(), and Bomberman.GameBoard.Update().
Monsters
List<Monster> Bomberman.GameBoard.Monsters = new List<Monster>() get private set
The players on the board (check for alive)
Definition at line 105 of file GameBoard.cs.
 { get; private set; } = new List<Monster>();
Referenced by Bomberman.Bomb.BlowUp(), Bomberman.GameBoard.CreateBoard(), Bomberman.Bomb.ExpandExplosion(), and Bomberman.GameBoard.LoadState().
Paused
bool Bomberman.GameBoard.Paused = false get private set
The game is paused
Definition at line 110 of file GameBoard.cs.
 { get; private set; } = false;
Referenced by Persistance.GameSave.GameSave(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.Pause(), Bomberman.GameBoard.Resume(), Bomberman.Bomb.Update(), Bomberman.GameBoard.Update(), Bomberman.Monster.Update(), Bomberman.MovingEntity.Update(), and Bomberman.Player.Update().
StartGameOverCounter
bool Bomberman.GameBoard.StartGameOverCounter = false get private set
The game over counter is started
Definition at line 115 of file GameBoard.cs.
 { get; private set; } = false;
Referenced by Bomberman.GameBoard.CheckGameOverEvent(), Persistance.GameSave.GameSave(), Bomberman.GameBoard.LoadState(), Bomberman.GameBoard.StartNextGame(), and Bomberman.GameBoard.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/GameBoard.cs