Bomberman: Bomberman.MonsterBrain Class Reference
Bomberman.MonsterBrain Class Reference abstract
The brain specified to control the monsters
Public Member Functions
virtual void InitBrain (Monster body, float accuracy=0.9f)
Inits the brain
abstract Direction ChangedCell ()
What direction to move towards when changed cells
Protected Member Functions
Direction NextTargetDir ()
Gets the next target direction
Protected Attributes
Monster body
The monster which the brain is controlling
Properties
float Accuracy [get, private set]
The accuracy of the monster (how frequently should it be full random)
Detailed Description
The brain specified to control the monsters
Definition at line 9 of file MonsterBrain.cs.
Member Function Documentation
InitBrain()
virtual void Bomberman.MonsterBrain.InitBrain (Monster body, float accuracy = 0.9f) inline virtual
Inits the brain
Parameters
body The parent monster
accuracy The accuracy of the brain
Reimplemented in Bomberman.StalkerBrain, and Bomberman.SmartyBrain.
Definition at line 26 of file MonsterBrain.cs.
         {
             this.body = body;
             this.Accuracy = accuracy;
         }
References Bomberman.MonsterBrain.Accuracy, and Bomberman.MonsterBrain.body.
Referenced by Bomberman.Monster.Init().
NextTargetDir()
Direction Bomberman.MonsterBrain.NextTargetDir () inline protected
Gets the next target direction
Returns
A new direction to move towards
Definition at line 37 of file MonsterBrain.cs.
         {
             List<Direction> possDir = new List<Direction>();
             for (int i = 0; i < 4; i++)
             {
                 if (body.DirectionPassable((Direction)i))
                 {
                     possDir.Add((Direction)i);
                 }
             }
             if (possDir.Count == 0)
             {
                 return (Direction)((byte)(body.CurrentDirection + 2) % 4);
             }
             return possDir[Config.RND.Next(0, possDir.Count)];
         }
References Bomberman.MonsterBrain.body, Bomberman.MovingEntity.CurrentDirection, Bomberman.MovingEntity.DirectionPassable(), and Bomberman.Config.RND.
Referenced by Bomberman.BasicBrain.ChangedCell(), Bomberman.GhostBrain.ChangedCell(), Bomberman.SmartyBrain.ChangedCell(), Bomberman.StalkerBrain.ChangedCell(), Bomberman.SmartyBrain.NearestPlayerDir(), and Bomberman.StalkerBrain.NearestPlayerDir().
ChangedCell()
abstract Direction Bomberman.MonsterBrain.ChangedCell () pure virtual
What direction to move towards when changed cells
Returns
A new direction to move towards
Implemented in Bomberman.StalkerBrain, Bomberman.SmartyBrain, Bomberman.GhostBrain, and Bomberman.BasicBrain.
Referenced by Bomberman.Monster.Init(), Bomberman.Monster.ReachedTarget(), and Bomberman.Monster.Update().
Member Data Documentation
body
Monster Bomberman.MonsterBrain.body protected
The monster which the brain is controlling
Definition at line 14 of file MonsterBrain.cs.
Referenced by Bomberman.BasicBrain.ChangedCell(), Bomberman.GhostBrain.ChangedCell(), Bomberman.SmartyBrain.ChangedCell(), Bomberman.StalkerBrain.ChangedCell(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Bomberman.MonsterBrain.InitBrain(), Bomberman.SmartyBrain.InitBrain(), Bomberman.StalkerBrain.InitBrain(), Bomberman.SmartyBrain.NearestPlayerDir(), Bomberman.StalkerBrain.NearestPlayerDir(), and Bomberman.MonsterBrain.NextTargetDir().
Property Documentation
Accuracy
float Bomberman.MonsterBrain.Accuracy get private set
The accuracy of the monster (how frequently should it be full random)
Definition at line 19 of file MonsterBrain.cs.
 { get; private set; }
Referenced by Bomberman.BasicBrain.ChangedCell(), Bomberman.GhostBrain.ChangedCell(), Bomberman.SmartyBrain.ChangedCell(), Bomberman.StalkerBrain.ChangedCell(), and Bomberman.MonsterBrain.InitBrain().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/MonsterBrain.cs