Bomberman: Bomberman.Obstacle Class Reference
Bomberman.Obstacle Class Reference
This is the class which contains the oblstacle's functions and datas
Public Member Functions
void SpawnBonus (BonusType bonusToSpawn)
This function is for testing purposes only!!! Spawn a specific bonus at the obstacle's position
override void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Initializes the obstacle
void ObstacleLoad (ObstacleSave obstacleSave)
Loads in the obstacle
bool Place (bool containBonus, int placerId=-1)
This method controls the placing of the obstacle
bool BlowUp (bool dropBonus=true)
This method controls the blowing up of the obstacle
void PlaceBomb (Bomb bombToPlace)
Places a bomb
void EraseBomb ()
Erases a bomb
Public Attributes
List< GameObject > bonusPrefabs
EventHandler BlownUp
The blown up event handler
Properties
bool Placed [get, private set]
Is the obstacle placed
bool HasBomb [get]
Does it contains a bomb
bool Destructible [get, private set]
Is it destructible
Bonus ContainingBonus [get, private set]
What type of bonus does it contains
bool NotPassable [get, private set]
Is it notpassable
int OwnerId = -1 [get, private set]
Who is the placed obstacle owner
Properties inherited from Bomberman.MapEntity
Position CurrentBoardPos [get, protected set]
The entity's current position on the Board's grid
MapEntityType EntityType [get, protected set]
The type of the entity
GameBoard GameBoard [get, protected set]
Reference to the parent board
Private Member Functions
void Awake ()
void DropBonus ()
Private Attributes
bool placed = false
bool destructible
bool notPassable
Sprite spriteWhenPlaced
Sprite spriteWhenBlownUp
SpriteRenderer spriteRenderer
Bomb placedBomb = null
Detailed Description
This is the class which contains the oblstacle's functions and datas
Definition at line 12 of file Obstacle.cs.
Member Function Documentation
Awake()
void Bomberman.Obstacle.Awake () inline private
Definition at line 71 of file Obstacle.cs.
         {
             this.spriteRenderer = this.gameObject.GetComponent<SpriteRenderer>();
         }
SpawnBonus()
void Bomberman.Obstacle.SpawnBonus (BonusType bonusToSpawn) inline
This function is for testing purposes only!!! Spawn a specific bonus at the obstacle's position
Definition at line 80 of file Obstacle.cs.
         {
             Bonus bonus = Instantiate(GameBoard.BonusPrefabs[bonusToSpawn], this.GameBoard.gameObject.transform).GetComponent<Bonus>();
             bonus.gameObject.transform.transform.localPosition = new Vector3(CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - CurrentBoardPos.Row * Config.CELLSIZE, 1);
             bonus.Init(MapEntityType.Bonus, this.GameBoard, new Position(this.CurrentBoardPos.Row, this.CurrentBoardPos.Col));
             bonus.Show();
         }
References Bomberman.Config.CELLSIZE, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bonus.Init(), DataTypes.Position.Row, and Bomberman.Bonus.Show().
Referenced by Bomberman.GameBoard.SpawnBonus().
DropBonus()
void Bomberman.Obstacle.DropBonus () inline private
Definition at line 90 of file Obstacle.cs.
         {
             if (ContainingBonus is not null)
             {
                 ContainingBonus.Show();
                 this.ContainingBonus = null;
             }
         }
References Bomberman.Obstacle.ContainingBonus, and Bomberman.Bonus.Show().
Referenced by Bomberman.Obstacle.BlowUp().
Init()
override void Bomberman.Obstacle.Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos) inline virtual
Initializes the obstacle
Reimplemented from Bomberman.MapEntity.
Definition at line 102 of file Obstacle.cs.
         {
             base.Init(entityType, gameBoard, CurrentPos);
         }
Referenced by Bomberman.GameBoard.CreateBoard(), and Bomberman.GameBoard.LoadState().
ObstacleLoad()
void Bomberman.Obstacle.ObstacleLoad (ObstacleSave obstacleSave) inline
Loads in the obstacle
Parameters
obstacleSave
Definition at line 111 of file Obstacle.cs.
         {
             if (obstacleSave.Placed)
             {
                 Place(false);
             }
             this.placed = obstacleSave.Placed;
             this.Destructible = obstacleSave.Destructible;
             this.notPassable = obstacleSave.NotPassable;
             this.OwnerId = obstacleSave.OwnerId;
             //Create a new bonus which it contains
             if (obstacleSave.ContainingBonusType != null)
             {
                 Bonus bonus = Instantiate(GameBoard.BonusPrefabs[obstacleSave.ContainingBonusType.Value], this.GameBoard.gameObject.transform).GetComponent<Bonus>();
                 bonus.gameObject.transform.transform.localPosition = new Vector3(CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - CurrentBoardPos.Row * Config.CELLSIZE, 1);
                 bonus.Init(MapEntityType.Bonus, this.GameBoard, new Position(this.CurrentBoardPos.Row, this.CurrentBoardPos.Col));
                 this.ContainingBonus = bonus;
             }
         }
References Bomberman.Config.CELLSIZE, DataTypes.Position.Col, Bomberman.Obstacle.ContainingBonus, Persistance.ObstacleSave.ContainingBonusType, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Obstacle.Destructible, Persistance.ObstacleSave.Destructible, Bomberman.Bonus.Init(), Persistance.ObstacleSave.NotPassable, Bomberman.Obstacle.OwnerId, Persistance.ObstacleSave.OwnerId, Bomberman.Obstacle.Place(), Persistance.ObstacleSave.Placed, and DataTypes.Position.Row.
Referenced by Bomberman.GameBoard.LoadState().
Place()
bool Bomberman.Obstacle.Place (bool containBonus, int placerId = -1) inline
This method controls the placing of the obstacle
Definition at line 134 of file Obstacle.cs.
         {
             if (this.Placed)
             {
                 return false;
             }
             this.Placed = true;
             this.OwnerId = placerId;
             if (spriteWhenPlaced is not null)
             {
                 spriteRenderer.sprite = spriteWhenPlaced;
             }
             else
             {
                 Debug.LogError("Sprite when placed is not set!");
             }
             if (containBonus)
             {
                 this.ContainingBonus = Instantiate(bonusPrefabs[Config.RND.Next(0, bonusPrefabs.Count)], this.GameBoard.gameObject.transform).GetComponent<Bonus>();
                 this.ContainingBonus.gameObject.transform.transform.localPosition = new Vector3(CurrentBoardPos.Col * Config.CELLSIZE, -2.5f - CurrentBoardPos.Row * Config.CELLSIZE, 1);
                 this.ContainingBonus.Init(MapEntityType.Bonus, this.GameBoard, new Position(this.CurrentBoardPos.Row, this.CurrentBoardPos.Col));
             }
             return true;
         }
References Bomberman.Obstacle.bonusPrefabs, Bomberman.Config.CELLSIZE, DataTypes.Position.Col, Bomberman.Obstacle.ContainingBonus, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bonus.Init(), Bomberman.Obstacle.OwnerId, Bomberman.Obstacle.Placed, Bomberman.Config.RND, DataTypes.Position.Row, Bomberman.Obstacle.spriteRenderer, and Bomberman.Obstacle.spriteWhenPlaced.
Referenced by Bomberman.GameBoard.CreateBoard(), Bomberman.Obstacle.ObstacleLoad(), and Bomberman.Player.PlaceObstacle().
BlowUp()
bool Bomberman.Obstacle.BlowUp (bool dropBonus = true) inline
This method controls the blowing up of the obstacle
Definition at line 164 of file Obstacle.cs.
         {
             if (!this.Placed)
             {
                 return false;
             }
             if (HasBomb)
             {
                 placedBomb.BlowUp();
                 placedBomb = null;
             }
             else if (dropBonus)
             {
                 DropBonus();
             }
             if (BlownUp is not null)
             {
                 BlownUp.Invoke(this, EventArgs.Empty);
                 BlownUp = null;
                 this.OwnerId = -1;
             }
             this.Placed = false;
             if (spriteWhenBlownUp is not null)
             {
                 spriteRenderer.sprite = spriteWhenBlownUp;
             }
             else
             {
                 Debug.LogError("Sprite when blown up is not set!");
             }
             return true;
         }
References Bomberman.Obstacle.BlownUp, Bomberman.Bomb.BlowUp(), Bomberman.Obstacle.DropBonus(), Bomberman.Obstacle.HasBomb, Bomberman.Obstacle.OwnerId, Bomberman.Obstacle.Placed, Bomberman.Obstacle.placedBomb, Bomberman.Obstacle.spriteRenderer, and Bomberman.Obstacle.spriteWhenBlownUp.
Referenced by Bomberman.Bomb.ExpandExplosion().
PlaceBomb()
void Bomberman.Obstacle.PlaceBomb (Bomb bombToPlace) inline
Places a bomb
Definition at line 204 of file Obstacle.cs.
         {
             //bandaid
             spriteRenderer.sprite = spriteWhenBlownUp;
             this.placedBomb = bombToPlace;
             this.Placed = true;
         }
References Bomberman.Obstacle.Placed, Bomberman.Obstacle.spriteRenderer, and Bomberman.Obstacle.spriteWhenBlownUp.
Referenced by Bomberman.Bomb.LoadBomb(), Bomberman.Player.PlaceBomb(), and Bomberman.GameBoard.SpawnBomb().
EraseBomb()
void Bomberman.Obstacle.EraseBomb () inline
Erases a bomb
Definition at line 216 of file Obstacle.cs.
         {
             //bandaid
             spriteRenderer.sprite = spriteWhenBlownUp;
             this.placedBomb = null;
             this.Placed = false;
         }
References Bomberman.Obstacle.Placed, and Bomberman.Obstacle.spriteWhenBlownUp.
Referenced by Bomberman.Bomb.BlownUp().
Member Data Documentation
placed
bool Bomberman.Obstacle.placed = false private
Definition at line 15 of file Obstacle.cs.
destructible
bool Bomberman.Obstacle.destructible private
Definition at line 28 of file Obstacle.cs.
notPassable
bool Bomberman.Obstacle.notPassable private
Definition at line 31 of file Obstacle.cs.
spriteWhenPlaced
Sprite Bomberman.Obstacle.spriteWhenPlaced private
Definition at line 34 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.Place().
spriteWhenBlownUp
Sprite Bomberman.Obstacle.spriteWhenBlownUp private
Definition at line 37 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.Obstacle.EraseBomb(), and Bomberman.Obstacle.PlaceBomb().
bonusPrefabs
List<GameObject> Bomberman.Obstacle.bonusPrefabs
Definition at line 40 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.Place(), and Bomberman.GameBoard.Start().
spriteRenderer
SpriteRenderer Bomberman.Obstacle.spriteRenderer private
Definition at line 42 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.Obstacle.Place(), and Bomberman.Obstacle.PlaceBomb().
placedBomb
Bomb Bomberman.Obstacle.placedBomb = null private
Definition at line 44 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.BlowUp().
BlownUp
EventHandler Bomberman.Obstacle.BlownUp
The blown up event handler
Definition at line 69 of file Obstacle.cs.
Referenced by Bomberman.Obstacle.BlowUp(), and Bomberman.Player.PlaceObstacle().
Property Documentation
Placed
bool Bomberman.Obstacle.Placed get private set
Is the obstacle placed
Definition at line 20 of file Obstacle.cs.
 { get => placed; private set => placed = value; }
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.MovingEntity.DirectionPassable(), Bomberman.Obstacle.EraseBomb(), Bomberman.Bomb.ExpandExplosion(), PathFinding.BFS.GetPathToSearched(), Bomberman.Obstacle.Place(), Bomberman.Player.PlaceBomb(), Bomberman.Obstacle.PlaceBomb(), Bomberman.Player.PlaceObstacle(), Persistance.ObstacleSave.SaveObstacle(), and Bomberman.Player.Update().
HasBomb
bool Bomberman.Obstacle.HasBomb get
Does it contains a bomb
Definition at line 25 of file Obstacle.cs.
 { get => placedBomb is not null; }
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.GhostBrain.DirectionTotallyImpassable(), Bomberman.Monster.Move(), and Bomberman.Player.Update().
Destructible
bool Bomberman.Obstacle.Destructible get private set
Is it destructible
Definition at line 49 of file Obstacle.cs.
 { get => destructible; private set => destructible = value; }
Referenced by Bomberman.Bomb.ExpandExplosion(), Bomberman.Obstacle.ObstacleLoad(), and Persistance.ObstacleSave.SaveObstacle().
ContainingBonus
Bonus Bomberman.Obstacle.ContainingBonus get private set
What type of bonus does it contains
Definition at line 54 of file Obstacle.cs.
 { get; private set; }
Referenced by Bomberman.Obstacle.DropBonus(), Bomberman.Obstacle.ObstacleLoad(), Bomberman.Obstacle.Place(), and Persistance.ObstacleSave.SaveObstacle().
NotPassable
bool Bomberman.Obstacle.NotPassable get private set
Is it notpassable
Definition at line 59 of file Obstacle.cs.
 { get => notPassable; private set => notPassable = value; }
Referenced by Bomberman.MovingEntity.DirectionPassable(), and Persistance.ObstacleSave.SaveObstacle().
OwnerId
int Bomberman.Obstacle.OwnerId = -1 get private set
Who is the placed obstacle owner
Definition at line 64 of file Obstacle.cs.
 { get; private set; } = -1;
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.Obstacle.ObstacleLoad(), Bomberman.Obstacle.Place(), and Persistance.ObstacleSave.SaveObstacle().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/Obstacle.cs