Bomberman: Bomberman.Bomb Class Reference
Bomberman.Bomb Class Reference
Controls how the bomb behaves in the game
Public Member Functions
void Place (Position whereToPlace, int radius)
Places the bomb at the given place
void LoadBomb (BombSave bombSave)
Loads the bombSave
void PlaceByGameBoard (Position whereToPlace, int radius, bool endless=false)
Place a bomb which blows up instantly
void BlowUp ()
Singnals the bomb to start blowing up
Public Member Functions inherited from Bomberman.MapEntity
virtual void Init (MapEntityType entityType, GameBoard gameBoard, Position CurrentPos)
Inits the entity should be called right after creating the entity
Public Attributes
AudioSource audioPlayer
Properties
int BlastRadius [get, private set]
How far does the bomb is blasting
bool Placed [get, private set]
Is the bomb is currently placed and active
float BombTimer [get, private set]
The bomb's internal timer
float TimeTillBlow = Config.BOMBBLOWTIME [get, private set]
How long does the bomb take to blow up
bool Detonable = false [get, set]
Is the bomb detonable
Properties inherited from Bomberman.MapEntity
Position CurrentBoardPos [get, protected set]
The entity's current position on the Board's grid
MapEntityType EntityType [get, protected set]
The type of the entity
GameBoard GameBoard [get, protected set]
Reference to the parent board
Private Member Functions
void Awake ()
void Update ()
void ExpandExplosion ()
void BlownUp ()
Private Attributes
List< GameObject > blowUpVisuals = new List<GameObject>()
The blow up visuals (order is Left, Up, Right, Down)
Dictionary< Direction, bool > ongoingExplosions = new Dictionary<Direction, bool>()
The directions where the explosion is spreading
bool bombBlowingUp = false
int currentRange = 0
float explosionSpreadTime = Config.BOMBEXPLOSIONSPREADSPEED
Detailed Description
Controls how the bomb behaves in the game
Definition at line 13 of file Bomb.cs.
Member Function Documentation
Awake()
void Bomberman.Bomb.Awake () inline private
Definition at line 63 of file Bomb.cs.
         {
             ongoingExplosions.Add(Direction.Left, false);
             ongoingExplosions.Add(Direction.Up, false);
             ongoingExplosions.Add(Direction.Right, false);
             ongoingExplosions.Add(Direction.Down, false);
         }
References Bomberman.Bomb.ongoingExplosions.
Update()
void Bomberman.Bomb.Update () inline private
Definition at line 72 of file Bomb.cs.
         {
             if (GameBoard.Paused)
             {
                 return;
             }
             //If the bomb is active
             if (Placed)
             {
                 BombTimer += Time.deltaTime;
                 //If the bomb is blowing up expand it's destruction
                 if (bombBlowingUp)
                 {
                     if (BombTimer >= explosionSpreadTime)
                     {
                         ++currentRange;
                         if (currentRange <= BlastRadius)
{
                             ExpandExplosion();
                         }
                         else
{
                             BlownUp();
                         }
                         BombTimer = 0f;
                     }
                 }
                 //Otherwise check if it is ready to blow
                 else
                 {
                     if (BombTimer >= TimeTillBlow && !Detonable)
                     {
                         BlowUp();
                     }
                 }
             }
         }
References Bomberman.Bomb.BlastRadius, Bomberman.Bomb.BlownUp(), Bomberman.Bomb.BlowUp(), Bomberman.Bomb.bombBlowingUp, Bomberman.Bomb.BombTimer, Bomberman.Bomb.currentRange, Bomberman.Bomb.Detonable, Bomberman.Bomb.ExpandExplosion(), Bomberman.Bomb.explosionSpreadTime, Bomberman.GameBoard.Paused, Bomberman.Bomb.Placed, and Bomberman.Bomb.TimeTillBlow.
ExpandExplosion()
void Bomberman.Bomb.ExpandExplosion () inline private
Definition at line 114 of file Bomb.cs.
         {
             for (Direction i = 0; i <= Direction.Down; i++)
             {
                 //Should we spread the bomb's explosion towards that direction
                 if (!ongoingExplosions[i])
                 {
                     continue;
                 }
                 //Get the cell in that direction
                 Vector3 newPosition = Vector3.zero;
                 Vector3 newScale = Vector3.zero;
                 Obstacle cell = null;
                 //According to the direction adjust the transforms and get the appropiate cell of the gameboard
                 switch (i)
                 {
                     case Direction.Left:
                         cell = GameBoard.Cells[CurrentBoardPos.Row, CurrentBoardPos.Col - 1 * currentRange];
                         newPosition = new Vector3(-0.5f * currentRange, 0);
                         newScale = new Vector3(1 * (currentRange + 1), 1);
                         break;
                     case Direction.Up:
                         cell = GameBoard.Cells[CurrentBoardPos.Row - 1 * currentRange, CurrentBoardPos.Col];
                         newPosition = new Vector3(0, +0.5f * currentRange);
                         newScale = new Vector3(1, 1 * (currentRange + 1));
                         break;
                     case Direction.Right:
                         cell = GameBoard.Cells[CurrentBoardPos.Row, CurrentBoardPos.Col + 1 * currentRange];
                         newPosition = new Vector3(0.5f * currentRange, 0);
                         newScale = new Vector3(1 * (currentRange + 1), 1);
                         break;
                     case Direction.Down:
                         cell = GameBoard.Cells[CurrentBoardPos.Row + 1 * currentRange, CurrentBoardPos.Col];
                         newPosition = new Vector3(0, -0.5f * currentRange);
                         newScale = new Vector3(1, 1 * (currentRange + 1));
                         break;
                     case Direction.None:
                         break;
                     default:
                         break;
                 }
                 //Based on the type of the cell spread the explosion or not
                 bool spreadIt = false;
                 if (cell.Placed)
                 {
                     //If the block can be blown up blow it up
                     if (cell.Destructible)
                     {
                         cell.BlowUp(true);
                         ongoingExplosions[i] = false;
                         spreadIt = true;
                     }
                     //Otherwise just skip this side for the rest of the bomb blow up cycle
                     else
                     {
                         ongoingExplosions[i] = false;
                         continue;
                     }
                 }
                 else
                 {
                     spreadIt = true;
                 }
                 //Adjust the visuals positions
                 if (spreadIt)
                 {
                     foreach (var item in this.GameBoard.Players)
                     {
                         if (item.CurrentBoardPos.Equals(cell.CurrentBoardPos))
{
                             item.Kill();
                         }
                     }
                     foreach (var item in this.GameBoard.Monsters)
                     {
                         if (item.CurrentBoardPos.Equals(cell.CurrentBoardPos))
{
                             item.Kill();
                         }
                     }
                     blowUpVisuals[(int)i].transform.localPosition = newPosition;
                     blowUpVisuals[(int)i].transform.localScale = newScale;
                 }
             }
         }
References Bomberman.Obstacle.BlowUp(), Bomberman.Bomb.blowUpVisuals, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bomb.currentRange, Bomberman.Obstacle.Destructible, Bomberman.GameBoard.Monsters, Bomberman.Bomb.ongoingExplosions, Bomberman.Obstacle.Placed, Bomberman.GameBoard.Players, and DataTypes.Position.Row.
Referenced by Bomberman.Bomb.PlaceByGameBoard(), and Bomberman.Bomb.Update().
BlownUp()
void Bomberman.Bomb.BlownUp () inline private
Definition at line 209 of file Bomb.cs.
         {
             this.GameBoard.Cells[this.CurrentBoardPos.Row, this.CurrentBoardPos.Col].EraseBomb();
             Debug.Log("Bumm");
             this.gameObject.SetActive(false);
             this.Placed = false;
         }
References Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Obstacle.EraseBomb(), Bomberman.Bomb.Placed, and DataTypes.Position.Row.
Referenced by Bomberman.Bomb.PlaceByGameBoard(), and Bomberman.Bomb.Update().
Place()
void Bomberman.Bomb.Place (Position whereToPlace, int radius) inline
Places the bomb at the given place
Parameters
whereToPlace The row and col of where to place the bomb on the board
radius How far does the bomb's radius is
Definition at line 223 of file Bomb.cs.
         {
             //Reset the bomb's parameters
             this.BlastRadius = radius;
             this.bombBlowingUp = false;
             this.Placed = true;
             this.explosionSpreadTime = (float)Config.BOMBEXPLOSIONSPREADSPEED / (float)radius;
             this.gameObject.SetActive(true);
             this.currentRange = 0;
             this.CurrentBoardPos = whereToPlace;
             this.gameObject.transform.localPosition = new Vector3(whereToPlace.Col * Config.CELLSIZE, -2.5f - whereToPlace.Row * Config.CELLSIZE, 1);
             //Reset the visuals and their parameters
             for (Direction i = 0; i <= Direction.Down; i++)
             {
                 blowUpVisuals[(int)i].SetActive(false);
                 blowUpVisuals[(int)i].transform.localScale = Vector3.one;
                 blowUpVisuals[(int)i].transform.localPosition = Vector3.zero;
                 ongoingExplosions[(i)] = true;
             }
             BombTimer = 0;
             //throw new System.NotImplementedException();
         }
References Bomberman.Bomb.BlastRadius, Bomberman.Bomb.blowUpVisuals, Bomberman.Config.BOMBEXPLOSIONSPREADSPEED, Bomberman.Bomb.BombTimer, Bomberman.Config.CELLSIZE, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Bomberman.Bomb.ongoingExplosions, Bomberman.Bomb.Placed, and DataTypes.Position.Row.
Referenced by Bomberman.Bomb.LoadBomb(), Bomberman.Player.PlaceBomb(), and Bomberman.Bomb.PlaceByGameBoard().
LoadBomb()
void Bomberman.Bomb.LoadBomb (BombSave bombSave) inline
Loads the bombSave
Definition at line 252 of file Bomb.cs.
         {
             if (bombSave.Placed)
             {
                 this.Place(bombSave.CurrentBoardPos, bombSave.BlastRadius);
                 GameBoard.Cells[this.CurrentBoardPos.Row, this.CurrentBoardPos.Col].PlaceBomb(this);
             }
             this.BombTimer = bombSave.BombTimer;
             this.TimeTillBlow = bombSave.TimeTillBlow;
             this.Detonable = bombSave.Detonable;
         }
References Persistance.BombSave.BlastRadius, Bomberman.Bomb.BombTimer, Persistance.BombSave.BombTimer, Bomberman.GameBoard.Cells, DataTypes.Position.Col, Bomberman.MapEntity.CurrentBoardPos, Persistance.MapEntitySave.CurrentBoardPos, Bomberman.Bomb.Detonable, Persistance.BombSave.Detonable, Bomberman.Bomb.Place(), Bomberman.Obstacle.PlaceBomb(), Persistance.BombSave.Placed, DataTypes.Position.Row, Bomberman.Bomb.TimeTillBlow, and Persistance.BombSave.TimeTillBlow.
Referenced by Bomberman.Player.LoadPlayer().
PlaceByGameBoard()
void Bomberman.Bomb.PlaceByGameBoard (Position whereToPlace, int radius, bool endless = false) inline
Place a bomb which blows up instantly
Parameters
whereToPlace Where to place the bomb
radius The size of the explosion
Definition at line 270 of file Bomb.cs.
         {
             Place(whereToPlace, radius);
             if (endless)
             {
                 TimeTillBlow = float.MaxValue;
                 return;
             }
             BlowUp();
             for (int i = 0; i < radius; i++)
             {
                 ++currentRange;
                 ExpandExplosion();
             }
             BlownUp();
             Destroy(this.gameObject);
         }
References Bomberman.Bomb.BlownUp(), Bomberman.Bomb.BlowUp(), Bomberman.Bomb.currentRange, Bomberman.Bomb.ExpandExplosion(), Bomberman.Bomb.Place(), and Bomberman.Bomb.TimeTillBlow.
Referenced by Bomberman.GameBoard.SpawnBomb().
BlowUp()
void Bomberman.Bomb.BlowUp () inline
Singnals the bomb to start blowing up
Definition at line 292 of file Bomb.cs.
         {
             //Sound effect
             audioPlayer.Play();
             bombBlowingUp = true;
             BombTimer = 0f;
             foreach (var item in this.GameBoard.Players)
             {
                 if (item.CurrentBoardPos.Equals(this.CurrentBoardPos))
                 {
                     item.Kill();
                 }
             }
             foreach (var item in this.GameBoard.Monsters)
             {
                 if (item.CurrentBoardPos.Equals(this.CurrentBoardPos))
                 {
                     item.Kill();
                 }
             }
             for (Direction i = 0; i <= Direction.Down; i++)
             {
                 blowUpVisuals[(int)i].SetActive(true);
             }
         }
References Bomberman.Bomb.audioPlayer, Bomberman.Bomb.blowUpVisuals, Bomberman.Bomb.bombBlowingUp, Bomberman.Bomb.BombTimer, Bomberman.GameBoard.Monsters, and Bomberman.GameBoard.Players.
Referenced by Bomberman.Obstacle.BlowUp(), Bomberman.Player.PlaceBomb(), Bomberman.Bomb.PlaceByGameBoard(), and Bomberman.Bomb.Update().
Member Data Documentation
blowUpVisuals
List<GameObject> Bomberman.Bomb.blowUpVisuals = new List<GameObject>() private
The blow up visuals (order is Left, Up, Right, Down)
Definition at line 19 of file Bomb.cs.
Referenced by Bomberman.Bomb.BlowUp(), Bomberman.Bomb.ExpandExplosion(), and Bomberman.Bomb.Place().
audioPlayer
AudioSource Bomberman.Bomb.audioPlayer
Definition at line 21 of file Bomb.cs.
Referenced by Bomberman.Bomb.BlowUp().
ongoingExplosions
Dictionary<Direction, bool> Bomberman.Bomb.ongoingExplosions = new Dictionary<Direction, bool>() private
The directions where the explosion is spreading
Definition at line 26 of file Bomb.cs.
Referenced by Bomberman.Bomb.Awake(), Bomberman.Bomb.ExpandExplosion(), and Bomberman.Bomb.Place().
bombBlowingUp
bool Bomberman.Bomb.bombBlowingUp = false private
Definition at line 29 of file Bomb.cs.
Referenced by Bomberman.Bomb.BlowUp(), and Bomberman.Bomb.Update().
currentRange
int Bomberman.Bomb.currentRange = 0 private
Definition at line 32 of file Bomb.cs.
Referenced by Bomberman.Bomb.ExpandExplosion(), Bomberman.Bomb.PlaceByGameBoard(), and Bomberman.Bomb.Update().
explosionSpreadTime
float Bomberman.Bomb.explosionSpreadTime = Config.BOMBEXPLOSIONSPREADSPEED private
Definition at line 35 of file Bomb.cs.
Referenced by Bomberman.Bomb.Update().
Property Documentation
BlastRadius
int Bomberman.Bomb.BlastRadius get private set
How far does the bomb is blasting
Definition at line 40 of file Bomb.cs.
 { get; private set; }
Referenced by Bomberman.Bomb.Place(), Persistance.BombSave.SaveBomb(), and Bomberman.Bomb.Update().
Placed
bool Bomberman.Bomb.Placed get private set
Is the bomb is currently placed and active
Definition at line 45 of file Bomb.cs.
 { get; private set; }
Referenced by Bomberman.Player.AllTheBombsPlaced(), Bomberman.Bomb.BlownUp(), Bomberman.Bomb.Place(), Bomberman.Player.PlaceBomb(), Persistance.BombSave.SaveBomb(), and Bomberman.Bomb.Update().
BombTimer
float Bomberman.Bomb.BombTimer get private set
The bomb's internal timer
Definition at line 50 of file Bomb.cs.
 { get; private set; }
Referenced by Bomberman.Bomb.BlowUp(), Bomberman.Bomb.LoadBomb(), Bomberman.Bomb.Place(), Persistance.BombSave.SaveBomb(), and Bomberman.Bomb.Update().
TimeTillBlow
float Bomberman.Bomb.TimeTillBlow = Config.BOMBBLOWTIME get private set
How long does the bomb take to blow up
Definition at line 55 of file Bomb.cs.
 { get; private set; } = Config.BOMBBLOWTIME;
Referenced by Bomberman.Bomb.LoadBomb(), Bomberman.Bomb.PlaceByGameBoard(), Persistance.BombSave.SaveBomb(), and Bomberman.Bomb.Update().
Detonable
bool Bomberman.Bomb.Detonable = false get set
Is the bomb detonable
Definition at line 60 of file Bomb.cs.
 { get; set; } = false;
Referenced by Bomberman.Bomb.LoadBomb(), Bomberman.Player.OnCollisionEnter2D(), Persistance.BombSave.SaveBomb(), and Bomberman.Bomb.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Game/Bomb.cs